### ISSUE TITLE
Comment Style /** ... */ vs //

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1004]
This issue can be for future discussion, post TS migration.

I've noticed that we are not consistent with the way methods are commented. Many times the /** */ vs // styles are intermixed within the same file. :-) Should we standardize on the way we document methods? 

For example in music.ts:

```
  /* Returns the interval of a note, given a diatonic scale.
   *
   * E.g., Given the scale C, and the note E, returns M3
   */
  getIntervalBetween(note1: number, note2: number, direction: number = 1): number {
    if (direction !== 1 && direction !== -1) {
      throw new Vex.RERR('BadArguments', `Invalid direction: ${direction}`);
    }
    ...
    return difference;
  }

  // Create a scale map that represents the pitch state for a
  // `keySignature`. For example, passing a `G` to `keySignature` would
  // return a scale map with every note naturalized except for `F` which
  // has an `F#` state.
  createScaleMap(keySignature: string): Record<string, string> {
    ...

```

In note.ts:

```
  // Get and set spacing to the left and right of the notes.
  getLeftDisplacedHeadPx(): number {
    return this.leftDisplacedHeadPx;
  }
  ...

  /** Returns true if this note has no duration (e.g., bar notes, spacers, etc.) */
  shouldIgnoreTicks(): boolean {
    return this.ignore_ticks;
  }

```

**Comment by ronyeh** [comment]
Even though I personally prefer the look of multiline comments starting with // ...

It looks like Microsoft is suggesting this standard:

https://tsdoc.org/play
https://github.com/microsoft/tsdoc/
https://github.com/microsoft/tsdoc/tree/master/tsdoc

**TypeDoc** is a popular tool that seems to mostly follow the TSDoc standard proposal:
https://typedoc.org/guides/doccomments/

So I guess it's a good idea to move toward the /** */ style of multi-line comments.

At some point we could use TypeDoc to generate documentation for the VexFlow API. We could even keep docco around to preserve the literate style documentation as an alternate way for developers to learn VexFlow.

**Comment by mscuthbert** [comment]
I don't think it's a matter of multiline vs single line.  Use two stars if the lines are intended to appear in the documentation, and one star or `//` if it is for developer reference only.  Sometimes there are multiline comments intended for devs only, like explaining how a complex algorithm works.  Maybe they should all be `//` lines, maybe one star, but not two-star.

**Comment by ronyeh** [comment]
Thanks @mscuthbert. I changed the title to reflect your note, but I think that we can (eventually) strive for more consistency throughout the code base.

My inclination would be to use multi-line double star comments at the top of classes and before methods and instance variables that need to be documented:
```
/**
 * This comment will be published as API docs.
 */
```
We can follow tsdoc standards, and generate API documentation using TypeDoc.

Then, internal to methods, we can use // style comments as you say, for VexFlow maintainers' eyes only.

These comments can look like:
````
doSomething() {
  // TODO: Handle via deep-copy in the future.

  // This horizontal adjustment is necessary because ...

  // Yes, this looks wrong but is actually correct due to legacy compatibility.
}
```


Right now we have code that sometimes looks like:
```
  // Generic function to add modifiers to a note
  //
  // Parameters:
  // * `index`: The index of the key that we're modifying
  // * `modifier`: The modifier to add
  addModifier(a: number | Modifier, b: number | Modifier): this {
  }
```

I think these should eventually be converted to /** */ to follow tsdoc convention.

**Comment by rvilarl** [comment]
The comments aiming to document the API ( the ones used by TypeDoc ) have to use the /** */ format. I stopped changing the comments because I noticed that the ammount of changes was breaking in many instances the comparison in git. This ended up showing the js file as deleted and the ts file as new.

In the end we will have to change all of those to /** */ in order to get the API documented.

We are using already typedoc. I generate every now and then updates of /typedoc.ts which contains exports of all the files where the documentation have to be generated. I use this file to make sure that typedoc does not document the file as different modules getting all the classes and interfaces in the same level.

**Comment by ronyeh** [comment]
Nice! I didn't even notice the typedoc.ts.

I guess once everything is migrated, we can go back to fix up the comment
styles. That way we can keep the diffs clean during migration.

**Comment by rvilarl** [comment]
@ronyeh I just made an update of typedoc with the new *.ts in master.
Use `npm start` and have a look at `index.html` in build/docs. `Element` has quite a fes comments already.

We can start anytime improving documentation on the files already migrated. I suggest to call `doc/file` the branches making sure that we only change comments.

I notice you prefer imperative rather than third person. For me both is ok.
@0xfe do you have a preference?

**Comment by 0xfe** [comment]
Thanks for the discussion folks. I don't have a strong opinion on this. As long as the comments are well thought out and readable, any style that isn't too burdensome is good for me. I tend to prefer `// ` because it's easy, and the editor autocompletes it, and only occasionally using `/*` for long comment blocks. (But again, no strong preference.)

@rvilarl re: grammar, I also don't have a strong opinion as long as it's readable. In particular I don't want non-native speakers to stress too much about it.

If you can agree on something that's lightweight, it's fine with me. :-)

**Comment by AaronDavidNewman** [comment]
Hi guys, is this issue also why the typedoc buid is failing? I thought it was in my environment, but I just pulled the latest vex tip and I still get this error.  Looks like our TS version is slightly ahead of what typedoc expects.

The library still works, I just get this error.

```
Running "typedoc:build" (typedoc) task
Warning: You are running with an unsupported TypeScript version! TypeDoc supports 3.9, 4.0, 4.1, 4.2
TypeDoc exiting with unexpected error:
TypeError: Cannot read property 'kind' of undefined
    at Object.isDeclaration ...
Warning: Task "typedoc:build" failed. Use --force to continue.

Aborted due to warnings.
```

Gruntfile.js:
`    "typescript": "^4.3.2",`

**Comment by rvilarl** [comment]
@AaronDavidNewman I realised now why I did not get the problem. I have seen in your PR #1020 that typescript is updated. This is good so `typedoc`should not stop us from upgrading.

**Comment by rvilarl** [comment]
@ronyeh  can we close now this one?
