### ISSUE TITLE
render_options (protected?)

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1070]
@0xfe @ronyeh Considering #348 I thought that `render_options` in many classes was a good candidate to start with. However I have realised that the tests do access this attribute although we declared it protected. This is one thing that we will realise anyway during the migration of the test to TypeScript.

 @0xfe do you want to leave `render_options` public? Is this part of the public API? Or would you prefer an access function?

**Comment by 0xfe** [comment]
It was meant to be public, but it was a really bad idea. I'd like to keep it internal, with some compatibility layer for those that depend on it.

**Comment by rvilarl** [comment]
> It was meant to be public, but it was a really bad idea. I'd like to keep it internal, with some compatibility layer for those that depend on it.

@0xfe Do you have an idea on how to make the compatibility layer? They are directly access as public attribute from the tests.

**Comment by 0xfe** [comment]
I meant make them available via access functions and log a warning to the console when they're used. The API will change here, and we can add some comments around using the new accessors instead.

**Comment by ronyeh** [comment]
Hi @mscuthbert and @rvilarl,

We had a related discussion recently over at: https://github.com/0xfe/vexflow/pull/1148#discussion_r717134986

What I got from that discussion is that the options objects should only be "inputs" to a class's constructor, and that after we validate all the options, there should not be a way to reach into the instance and retrieve the render_options.

However, I understand from @mscuthbert that as a VexFlow user, it is extremely useful to be able to reach into an instance to see its parameters (thickness, line number, positioning, etc) so that you can determine how to format a different stave item.

## Proposal for eliminating render_options
* options objects (e.g., render_options) can **only be provided as inputs** during construction of an instance.
* these options are individually validated, and assigned directly to internal instance variables. We completely eliminate `render_options` style objects from within VexFlow classes, and instead "flatten" the objects so that the validated parameters become individual instance variables of that object.
* these validated parameters have getters (and optionally setters), so that users like @mscuthbert can retrieve information about the instance.

Since folks seem to be wanting an October 4.0 release, I think we would have to do this post 4.0. However, this might be somewhat breaking. We'd have to determine whether that means 4.1, or 5.0.

Ideally, most of the changes would happen internally to each class. We would just introduce more getters/setters for the individual rendering parameters. The only breaking changes would be where we eliminate direct access to render_options.

> please note that protected has only been added to 4 classes (Beam, Note, Stavetie & TextBracket), in the other 13 classes, this attribute was already protected.

@rvilarl we need to remind ourselves that before March 2021, when you and I started working on this project, all member variables were effectively "public" even if Mohit didn't intend them to be. We probably introduced the `protected` labels during the TS migration. So we should consider how our 4.0 release will affect users of the project. I'm fine with introducing breaking changes (and we have done quite a few), but we need to accommodate the developers who use this project, like @mscuthbert and @sschmidTU and others.

Anyways, we should get more feedback, including from @0xfe.

Questions
* Should we make render_options protected and then provide individual accessors to each parameter?
* Should we eliminate render_options completely, and assign the validated parameters directly to instance variables (while providing the necessary accessors)?
* Something else?

**Comment by 0xfe** [comment]
Thanks for the discussion. IMO, `render_options` is a bit of a mess we need to dig out of, but we'll need to do it gently. Making it wholehog protected/accessor-only or eliminating completely is too disruptive to our users, in the context of this migration where there's already a lot of API changes.

Long term, I think we should eliminate it entirely and replace `render_options` with something better thought through. (I really like the idea of using more dynamic `ElementAttributes` because they're great for higher level libraries like VexTab and EasyScore, but you do lose type safety there, which is something we should manage.)

Near term, let's just mark it as deprecated for 4.0, and plan to migrate in a dot version (4.1 or 4.2.)

How does that sound?

**Comment by 0xfe** [comment]
Let's keep them public for consistency. And yes, inline where it makes sense -- that's a good idea.

**Comment by rvilarl** [comment]
Done #1184 ready to merge
