### ISSUE TITLE
generate_png_images complains about VFT

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1088]
@ronyeh  I have realised that after the migration of tests to TS, I get the following:

vexflow/tools/generate_png_images.js:50
VFT.RUN_CANVAS_TESTS = false;
                     ^

TypeError: Cannot set property 'RUN_CANVAS_TESTS' of undefined
    at Object.<anonymous> (/home/rodrigo/git/vexflow/tools/generate_png_images.js:50:22)

**Comment by ronyeh** [comment]
are you doing a test:reference?

I think it's because I had to add a hack into the generate_png_images.js to support both the old way of loading vexflow-tests.js, and the new way.

See:

https://github.com/0xfe/vexflow/blob/7a682f7075017ccdcebd30d06dcc0f9661126dd2/tools/generate_png_images.js#L31-L46


I will work on a PR fix now that the tests migration has been merged. It should be as simple as removing `scriptDir.includes('reference') || `

**Comment by ronyeh** [comment]
I fixed this issue with PR https://github.com/0xfe/vexflow/pull/1090

If you need to `npm run test:reference` before @0xfe has a chance to merge, you can manually patch your generage_png_images.js by removing `scriptDir.includes('reference') ||` from line 31.

**Comment by rvilarl** [comment]
Thanks
