### ISSUE TITLE
Consider whether instanceof checks will create problems for users

### ISSUE THREAD

**Issue by mscuthbert** [0xfe/vexflow#1096]
One thing I've noticed is appearing more in the Vexflow code after moving to TypeScript are more instanceof tests, which Typescript really likes (and helps with typing).  There's a significant downside of them when embedding Vexflow in large projects, which often appears with JQuery projects.

Say I'm using a program that uses Vexflow (OSMD, or music21j, or something) but I also use Vexflow directly in my project.  My code may look something like this:

```
import * as music21 from 'music21j';
import * as Vex from 'vexflow';

const vfn = <Vex.Flow.StaveNote> new music21.note.Note('C#').vexflowNote;
const staff = new Vex.Flow.Stave();
...  // etc. place vfn into staff, and finally something like:
staff.draw()
```

The problem is that as far as `staff` is concerned, `vfn instanceof Vex.Flow.StaveNote` is false!  Why?  Because most packaging systems will load `music21j` from its already compiled/packed form which includes its own copy of Vexflow.  Even if they are identical versions, etc., `instanceof` checks that `vfn.constructor === Vex.Flow.StaveNote` using triple-equal memory-location equality.   This can lead to some very subtle bugs that are hard to diagnose, even though there's no reason why a Vex.Flow.StaveNote loaded from one copy of Vexflow can't be processed by objects loaded from another copy of Vexflow (assuming they're the same or similar versions).

This happens quite often with projects involving JQuery (which somehow always gets loaded at least twice into every webpack...) where some routine will read something like:

```
getText(el: HTMLElement|JQuery<HTMLElement>) {
   let html_el: HTMLElement;
   if (el instanceof JQuery) { html_el = el[0]; } 
   else { html_el = el; } 
   return html_el.innerText;   // possible error:  JQuery element has no attribute innerText
}
```
...where el is a JQuery element that is not instanceof (someone else's) JQuery constructor.  And I'm afraid this will start happening in Vexflow as well.

**Comment by ronyeh** [comment]
This is precisely what happened with the flow.html test page while we were migrating tests to TS.

flow.html included vexflow-debug.js and also vexflow-tests.js. Since both were bundled separately by webpack, there ended up being two copies of VexFlow on the flow.html webpage.

And instanceof and strict equality checks started failing because Vex.Flow was not the same object as Flow, etc.


It's a good discussion to have. The big question is, should we support this case, where a webpage may have multiple (slightly incompatible) versions of VexFlow?

There are definitely benefits to the old flexible JS world where "if it walks like a ~~duck~~ StaveNote and it quacks like a StaveNote" then it might as well be a StaveNote.

33 of the classes have a CATEGORY property. For example:
```
  static get CATEGORY(): string {
    return 'gracenotes';
  }
```

So one idea would be to test against an object's .CATEGORY or something.

Possible Benefit: you could create a library that could churn out plain JS objects that are compatible with `GraceNote`, but do something slightly different. All it would have to do is have a .CATEGORY that returns 'gracenotes'.

Drawback: we would be sidestepping the main benefit of TypeScript, and basically reinventing our own type checking system (via string comparisons, or feature detection on whether a particular function exists on the object).

Is there something we could do with TypeScript interfaces instead of relying on `instanceof`?

... after some web searching ...

This might be related to our discussion: https://stackoverflow.com/questions/14425568/interface-type-check-with-typescript

So yeah, maybe we can strike a balance somehow. I personally love the benefits of TypeScript. However, I can see how TS can sometimes feel like Java where if you didn't subclass the exact class that I expect, then sorry you're out of luck.

There are real benefits of supporting duck typing or structural typing or feature detection, like in the Python, old school JS, or golang worlds.

p.s. sorry for rambling (it's late!). I just thought this was an interesting topic.

**Comment by ronyeh** [comment]
63 of the classes call `this.setAttribute('type', 'XXXXX');` in the constructor.

33 of the classes have a `getCategory(): string` method.

If we want to have a flexible type check system, perhaps we can write some utility methods like:

```
// eslint-disable-next-line
function isStaveNote(s: any): s is StaveNote {
  return (
    s instanceof StaveNote ||
    ('getCategory' in s && s.getCategory() === StaveNote.CATEGORY) ||
    ('getAttribute' in s && s.getAttribute('type') === 'StaveNote')
  );
}

```

See: https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

So maybe we just need a set of custom type guard functions, and then go replace all of our instanceof with our custom type guards?

**Comment by mscuthbert** [comment]
yeah -- losing the type narrowing that `instanceof` gives is a major pain.  The category part also doesn't work well with subclasses.

(in music21j we define a static (class) property of className for each class:

```
    static get className() { return 'music21.chord.Chord'; }
```

and then there's a property `.classes` (and `.classSet`) that walks the prototype chain and creates the class list for any class.  So `ch = new music21.chord.Chord();  ch.classes` returns `['Chord', 'NotRest', 'GeneralNote', 'Music21Object', 'ProtoM21Object', 'object']`  -- it's boring as anything, but if you're interested in how this is done see music21j's src/prebase.ts file.

We have a `obj.isClassOrSubclass('music21.chord.Chord')` or `obj.isClassOrSubclass(music21.chord.Chord)` (no string marking) that can figure out if an object is another instance of the object.  One of the things that I think might be possible with this system is to write something like:

```
isClassOrSubclass<T>(this: any, classType: string|Type): this is T {}
```

which would be a little bit redundant, because you'd then write:

```
if (maybe_stavenote.isClassOrSubclass<Vex.Flow.StaveNote>('StaveNote')) {
    // access StaveNote functions here.
}
```

it might also be possible to make that routine smart enough to do something like this:

```
isClassOrSubclass<T>(this: any, classType: string|Type):this is T {
    if (!(typeof classType === 'string')) { 
        // we've passed in a Class itself...uh oh, must check for whether they're the same type of thing...
        const myVexFlowCategories = classType.classes
        const thisObjectCategories = this.classes
        return array_equal(myVexFlowCategories, thisObjectCategories);
    }
```

or something like that.

**Comment by ronyeh** [comment]
This is what I arrived at after ........ some digging around. It's not the prettiest, but I think it's the right solution if we need a more flexible alternative to `instanceof`.

```
type Constructor<T> = Function & { prototype: T };

/**
 * Use this instead of `instanceof` as a more flexible type guard.
 * @param obj
 * @param ClassName
 * @returns true if `obj` is likely an instance of `ClassName`.
 */
export function isKindOf<T>(obj: any, ClassName: Constructor<T>): obj is T {
  // e.g., if obj is undefined or a number
  if (typeof obj !== 'object') {
    return false;
  }

  return (
    obj instanceof ClassName ||
    ClassName.name === obj.constructor.name ||
    ('getCategory' in obj && obj.getCategory() === (ClassName as any).CATEGORY)
  );
}
```

**Comment by ronyeh** [comment]
> property .classes (and .classSet) that walks the prototype chain and creates the class list for any class.
> ... figure out if an object is another instance of the object. 

whaaa?!! so you implemented `instanceof`? :-9 Just kidding (only sorta).

**Comment by 0xfe** [comment]
Thanks for raising this @mscuthbert.

Ron, I like your `isKindOf`, and I think it's a good alternative (maybe rename to `isCategory` or `isVexFlowCategory`.) I think, in addition, we should look at the existing `instanceof` checks and see what they're actually trying to do. I suspect many of them can be replaced with some from of interface check (either with TS interfaces, or with explicit duck-typing tests looking for property/method names.) If we start with a list of the uses, maybe we can find some patterns and possibly even eliminate some of them.

> The big question is, should we support this case, where a webpage may have multiple (slightly incompatible) versions of VexFlow?

I don't think we should. It's a heavy lift for not a lot of benefit.

**Comment by ronyeh** [comment]
OK I can rename to isCategory. In my current PR I have it in util.ts because `check<T>(x?: T): T` is also there. Or do you think it should be under the Vex.* namespace and be in `vex.ts`? Most of the utility methods in the Vex.* namespace seem to be unused.

Overall, I agree that VexFlow shouldn't have the explicit goal of supporting multiple VexFlow libraries on the same page.

However, if major users of VexFlow come to us with actionable advice to make their lives easier, then we can try our best to accommodate. 

We can see if we can eliminate most uses of `instanceof`, and in the cases that we cannot, we can try to use `isCategory` which works well as a type guard.
