### ISSUE TITLE
Tests - run.ts produces different visual output if the imports and test cases are sorted alphabetically

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1109]
I tried cleaning up the run.ts tests by sorting everything alphabetically.

However, this changes the color of the stave lines in some of the tests. Perhaps the stave lines' color is initialized improperly either before or after the sort, due to the ordering of dependencies/imports?

Need to investigate this... as ideally the test suite should be more robust to sorting of imports.

**Comment by 0xfe** [comment]
Good catch! The test suite should be robust to this. Part of the problem here is that we have some global configuration state.

I think we can do two things here:

- Add a `VF.reset()` that restores all globals to it's original state. (Ideally, we'll have a class to capture all the globals to simplify this.
- Update our test harness (`VexFlowTests.runTest(...)`) code to call `VF.reset()` before each test begins.

Does that make sense?
