### ISSUE TITLE
FormatOptions vs FormatterOptions

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1149]
https://github.com/0xfe/vexflow/blob/44605d07e6fe27eed4f10c4ec94bfb0e9b12f692/src/formatter.ts#L29-L41

While cleaning up the Partials, I ran across `formatter.ts` which has two exported interfaces: `FormatOptions` and `FormatterOptions`. It confused me at first sight, and probably would confuse a new VexFlow user as well.

This is a reminder to myself to discuss w/ Rodrigo and Mohit to see if there's a better name for one of the interfaces. Neither type existed 6 months ago, so it's not a huge risk to rename.

If we ultimately decide there's no better name for either interface, I'll close this issue.

**Comment by ronyeh** [comment]
Similarly, `system.ts` has `SystemOptions` and `SystemParams` :-) Both are exported interfaces.

I'll have to think about these when I'm more awake. :-)

**Comment by mscuthbert** [comment]
Great catch. 

Btw -- how close do people who have been working hard on this all summer/fall feel we are to making a 4.0 release (or at least beta) from all this amazing work?  Maybe saying that InterfaceNames/TypeScript features can change during the 4.0 cycle?  I have a couple of projects that I like to install Vexflow from npm directly on rather than building from master, but so many amazing things have been added/changed that I'm itching to use them.  :-)

**Comment by ronyeh** [comment]
Can you start a discussion thread and ping relevant maintainers so we can reach consensus about what we want to accomplish before 4.0.0?

At the moment, you could actually npm install directly from your public GitHub fork. 

Here are general things I'd like to accomplish:
* Review all instance variables to see if they should be public, or protected with accessors, or in the extreme cases, private to the class or private to the JS module (declared above the class). In 3.0.9, everything was effectively public.
* Review exported interfaces to see if there is any low hanging fruit.... Obvious interface name improvements, obvious delineation between required params or optional params.
* Documentation! At least document the most important methods.
* Finalize any breaking API changes. There might be some old crusty methods that are candidate for removal. For example, we have two substantially similar methods for drawing a vertical barline on a stave. After Rodrigo's bug fix, they are now identical. Maybe just delete one of the two methods?
* Test test test test test.....

Specific things I'd like to do:
* I have an improvement to .setFont that I'd like to get merged before 4.0.0. It brings our font API closer to the CSS font API, which it has always been very close to, but annoying different from. Hah. 
* Bump the OTF smufl font versions. Remove the noglyph glyphs.
* Explore improvements to the SVG path handling in collaboration with Tom. If this doesn't make it in before 4.0.0, that might be fine since ideally the changes are in the engine and not visible to end users (aka developers who npm install vexflow).

I'd love to discuss this in an official discussion thread. We can work together to decide what is or is not included in the 4.0.0 release. Once those features are in, and the bugs ironed out, we can ship it.

**Comment by 0xfe** [comment]
+1 on starting a thread about this -- we're definitely overdue for 4.0.0, and it's easy to keep adding to its scope. It's okay to push some of these nice-to-have features into 4.1.

**Comment by ronyeh** [comment]
As a developer, I always like to feature creep. :-)

Objectively the most important thing is to nail down the public facing API
(exported methods, public fields, interfaces). We don't want any API
breakage after shipping 4.0.0 (although marking methods as deprecated is
fine for minor releases.)

**Comment by mscuthbert** [comment]
By thread people mean email?  Like on a mailing list?  It's been a long time since I've done that!

My feeling for 4.0 response to @ronyeh is:

- "Review all instance variables to see if they should be public" -- feeling is switching something public to private is a compatibility break in any case (the reverse direction is not true), so whether that happens in 4.0 or 5.0 is less important.  I feel like people are going to have enough code to migrate moving to 4.0 (esp. if they're coming from 1.2) that making them find workarounds for suddenly private interfaces that used to be public could hurt adoption.  Then we have a version to discuss what to make private and what not before the next breaking release.
- "Review exported interfaces to see if there is any low hanging fruit" -- agreed.
- "Documentation" -- vote is no.  Documentation improvements have been needed throughout Vexflow since the start, and will always be needed.  But one never documents without getting new ideas which uncover new bugs which take time, etc.  If we wait for docs to be done, v4 will take a long time to ship.  If we ship first, then people who aren't comfortable with this level of development can help with the docs.
- "Finalize any breaking API changes" absolutely.  But look for nearly identical methods and unite them -- that could take a long time without major advantages over doing in the next version.

Even though it's such a major accomplishment, there's no reason that v4 needs to be the major version number for very long.  I can imagine a world where v4 is out by early October and v5 is out by New Year just based on all the things we learn from having a larger usage base for v4.

starting the thread now, and will copy main parts of this discussion there.

**Comment by ronyeh** [comment]
Ah I meant on the GitHub discussions tab. That way the discussion can be
public.

**Comment by mscuthbert** [comment]
oops.  well, it’s on the mailing list too now.

**Comment by ronyeh** [comment]
Or if we don't like using GitHub discussions, we can open a GitHub issue
called 4.0.0. when we ship, we can close the issue!

**Comment by ronyeh** [comment]
I'm moving the 4.0.0 release discussion to: https://github.com/0xfe/vexflow/issues/1155
We'll close the issue once it's released.

**Comment by rvilarl** [comment]
@0xfe @ronyeh this should be an easy one to close, it is just deciding the proper names. My proposal:

- `SystemParams` -> `SystemStave`
- `...Options` class options provided to the constructor: `CrescendoParams` -> `CrescendoOptions`, `TextBracketParams` -> `TextBracketOptions`, 
- `...Params` group of parameters used on functions: `FormatOptions` -> `FormatParams`
