### ISSUE TITLE
SVGs don't render in ImageMagick correctly

### ISSUE THREAD

**Issue by tommadams** [0xfe/vexflow#1150]
ronyeh brought up in #1145 the fact that the visual regression currently doesn't test canvas rendering, which has recently been found to have a few bugs (#1126, #1145, #1142, #1140). I did a quick test and ran ImageMagick on the command line to try and diff some SVGs generated by `SVGContext` and none of them rendered correctly. It's possible that the SVGs are malformed somehow and browsers are just more forgiving than ImageMagick but we'll need to fix this before if we want to run visual regression tests on SVG output.

Here's the output from converting an SVG generated by `SVGContext` to PNG (`convert test.svg test.png`):
![imagemagick output](https://user-images.githubusercontent.com/7587269/134702937-84fadd27-096a-4fcc-9367-f2fb1d07dcb2.png)

At first glance it looks like all the glyphs might be missing.

**Comment by tommadams** [comment]
This actually does seem like a bug in ImageMagick, triggered by this line: https://github.com/0xfe/vexflow/blob/44605d07e6fe27eed4f10c4ec94bfb0e9b12f692/src/glyph.ts#L300

Every glyph already starts with a move command, so the extra `moveTo` at the beginning of the glyph `renderOutline` means that the glyph outlines always start with two moves. See this notehead for example (there are two `M` commands at the start):

```M723.6072721697672 430M723.6072721697672 431.6848C723.6072721697672 433.7908,725.3482321697671 435.0544,727.5384721697671 435.0544C731.1327121697672 435.0544,735.5412721697671 431.74096,735.5412721697671 428.3152C735.5412721697671 426.23728,733.9126321697671 424.9456,731.6100721697671 424.9456C727.1734321697671 424.9456,723.6072721697672 428.23096,723.6072721697672 431.6848```

If I delete the first redundant move, then ImageMagick renders the glyphs correctly.

I've gotta go do my day job now but I'll get back to this either this evening or over the weekend. Hopefully it should be as simple as deleting the `ctx.moveTo(x_pos, y_pos)` call.

**Comment by ronyeh** [comment]
I found this: https://stackoverflow.com/questions/9853325/how-to-convert-a-svg-to-a-png-with-imagemagick

It suggested using: https://github.com/shakiba/svgexport

I tried: 
```
npm install svgexport -g
svgexport test.svg test.png
```

Works great. :-)

So browsers, Affinity Designer, and svgexport work great. 

"svgexport is a Node.js module and command-line tool for exporting SVG files to PNG and JPEG, it uses Puppeteer for rendering SVG files."

**Comment by ronyeh** [comment]
While looking at this issue, I am reminded that our SVG outputs 15 decimal points of precision! :-)

For a simple VexFlow demo like this:

![output](https://user-images.githubusercontent.com/239113/134722659-364e600a-c172-425d-82b4-3219ca8c60d3.jpg)


The output SVG looks like this:
<img width="1493" alt="SVG" src="https://user-images.githubusercontent.com/239113/134722446-63bb9746-cdcb-4476-a783-18844a5dbfc6.png">


The PNG is 3KB and the SVG is 8KB of text.

So if we end up wanting to do SVG path diffing, we might consider rounding down to like 3 or 4 decimal points of precision.

I found this educational thread over at the d3 project:
https://github.com/d3/d3-path/issues/10#issuecomment-275373270

https://github.com/d3/d3-path/issues/10#issuecomment-613939201

https://github.com/d3/d3-path/issues/10


The discussion (from a while ago) suggests that maybe the Chrome debugging experience suffers with excessively long SVG path strings.

In any case, SVG file sizes would be a bit smaller :-). Maybe we can round for the purposes of doing SVG diffing, since some of the comments suggest that different architectures might have tiny floating point differences that affect string diffing:

"The snapshot was generated on Mac but the unit tests were ran on Linux systems, and the floating point error makes the entire snapshot testing fail."
