### ISSUE TITLE
OSMD migration to vexflow 4.0: `any` required all over the place

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1217]
The migration of OSMD to vexflow 4.0 required a lot of `any`. I am particulary annoyed because with all these anys we lose the the benefits of TypeScript type checking.

See:

https://github.com/rvilarl/opensheetmusicdisplay/pull/2/files

**Comment by rvilarl** [comment]
I have been googling and I found the following article:

 https://basarat.gitbook.io/typescript/main-1/defaultisbad

This make me think to move away from:

`export default Vex;`

and protoype:
```
export * from './rendercontext';

export const Vex = {
...
```
With this approach I could import `RenderContext` and use it in OSMD without issues avoiding its related `any`

**Comment by rvilarl** [comment]
This would be a breaking change in current applications requiring:
`import { Vex } from "vexflow";`
rather than:
`import Vex  from "vexflow";`

But it has the big benefit to use:
`import { RenderContext, Vex } from "vexflow";`
in future applications (RenderContext is just an example).

**Comment by rvilarl** [comment]
@0xfe @mscuthbert @AaronDavidNewman @sschmidTU @ronyeh what do you think?

**Comment by AaronDavidNewman** [comment]
>> The migration of OSMD to vexflow 4.0 required a lot of any

Same with smoosic.  Isn't there a way to create a typescript declaration file?

https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

Then OSMD (and smoosic) could import @types/vex.  I don't know if this is an automatic process though.

>> This would be a breaking change 

It is not an either-or, is it?  You can use the types if you want the types, the code will have to change anyway.

**Comment by ronyeh** [comment]
Yes, the current version creates all the d.ts files. Let me send you an
example TS project that sees the types correctly.

**Comment by ronyeh** [comment]
Regarding default export or not, I don't mind either way. Last week I tried doing the no default exports approach:
`import { Vex } from "vexflow";`

But I realized I would be breaking old projects and we would have to change the documentation to reflect this new way. So, I reverted to the default export approach that we had in 3.0.9. 

Anyways, let me post my TS integration example, and we can iterate on how to make all the types easily accessible. We can copy approaches from other TS projects (e.g. Tone).

**Comment by 0xfe** [comment]
I would love to see some instructions on how we can use the current master branch with typescript and es6. We have a lot of documentation to update. Particularly the tutorials.

**Comment by rvilarl** [comment]
Can you point to an example? I mean a tutorial that needs update.

**Comment by AaronDavidNewman** [comment]
I don't think the tutorial uses typescript though.  So like `var notes:Note[] = [];` etc

**Comment by rvilarl** [comment]
I would suggest to move the tutorials to a tutorials directoy in the source code and point to this directory in the wiki. With that we would make sure that they are mantained and do work. What do you think? I know that Ron agrees on that we have been discussing it in the past.

**Comment by rvilarl** [comment]
After a long day of migration the attributes accessed by OSMD which are not public are the following:
```
      TS2445: Property 'note_heads' is protected and only accessible within class 'StaveNote' and its subclasses.
      TS2445: Property 'top_stave' is protected and only accessible within class 'StaveConnector' and its subclasses.
      TS2445: Property 'bottom_stave' is protected and only accessible within class 'StaveConnector' and its subclasses.
      TS2445: Property 'thickness' is protected and only accessible within class 'StaveConnector' and its subclasses.
      TS2445: Property 'x_shift' is protected and only accessible within class 'StaveConnector' and its subclasses.
      TS2445: Property 'options' is protected and only accessible within class 'Stave' and its subclasses.
      TS2445: Property 'font' is protected and only accessible within class 'TextBracket' and its subclasses.
      TS2445: Property 'position' is protected and only accessible within class 'TextBracket' and its subclasses.
      TS2445: Property 'start' is protected and only accessible within class 'TextBracket' and its subclasses.
      TS2445: Property 'preFormatted' is protected and only accessible within class 'Tickable' and its subclasses.
      TS2445: Property 'glyph' is protected and only accessible within class 'Note' and its subclasses.
 ```

**Comment by rvilarl** [comment]
> This would be a breaking change in current applications requiring: `import { Vex } from "vexflow";` rather than: `import Vex from "vexflow";`
> 
> But it has the big benefit to use: `import { RenderContext, Vex } from "vexflow";` in future applications (RenderContext is just an example).

I had to follow the approach above to get rid of the `any` in order to identify the accessed protected attributes.

**Comment by ronyeh** [comment]
In my TypeScript integration example project, I didn't have to change the way we import VexFlow. 

https://github.com/ronyeh/vexflow-example-typescript/blob/1378148f54c297d3b40c36a9730df86e2f20cd63/app.ts#L1

You can technically import as follows:

`import Vex, { RenderContext } from 'vexflow';`

Or you can do it on two separate lines. 

But I admit your approach looks slightly cleaner, even though it's a breaking change. 

@0xfe I submitted a PR to vextab that makes it work with my current 4.0.0 branch. As you can see, we actually haven't broken much of the public API from the perspective of that project. 

It looks like Rodrigo has discovered that OSMD uses some previously public member variables that we have since protected (post TS migration). For backwards compatibility we could just add read-only accessors.... Or we could make those variables public again. 

I can work with Aaron and Michael to help them migrate smoosic and music21j to VexFlow 4. 

Regarding docs and tutorials, my personal bias is that I would love for them all to live in the docs/ folder inside the repository. They can be markdown files that can be linked to directly from the wiki, and rendered by GitHub like how they render README.md files. 

Benefits of the current wiki approach:
- really fast and easy to write up something and publish it, even if you are not a VexFlow maintainer.

Benefits of keeping them inside the docs/ directory of the repository:
- Maintainers can code review any documentation changes, since they must be submitted as PRs 
- the tutorials and docs live alongside the code so it might be easier to verify that the example code is updated and compiles. (Recently I found some copy and paste typo bugs in the wiki example code. It is quite difficult to edit any non trivial code examples directly in the wiki editor.)

We can take a hybrid approach where community contributed tutorials and example code lives in the wiki, and can get promoted to official docs inside the repo. But mostly I feel like the wiki should be very short snippets and a collection of links to more extensive docs and demos and tutorials inside the repo. 



Last week I spent a lot of time improving the build process (with Rodrigo's help in testing) so that VexFlow can more easily integrate with both TypeScript projects and es6 projects. We are close, and the current results live in my 4.0.0-alpha branch. We will continue to submit PRs so that we can get all the improvements into the 0xfe master.

**Comment by rvilarl** [comment]
OSMD is now integrated with 4.0.0-alpha. I just used ts-ignore with the problems referenced above.

It does no longer work with PianoPlay :|

@sschmidTU debugging it together with my App would be to complex how should I check if the compiled OSMD is working?

**Comment by rvilarl** [comment]
Migration of OSMD done with all checks passed!

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1085

**Comment by rvilarl** [comment]
> After a long day of migration the attributes accessed by OSMD which are not public are the following:
> 
> ```
>       TS2445: Property 'note_heads' is protected and only accessible within class 'StaveNote' and its subclasses.
>       TS2445: Property 'top_stave' is protected and only accessible within class 'StaveConnector' and its subclasses.
>       TS2445: Property 'bottom_stave' is protected and only accessible within class 'StaveConnector' and its subclasses.
>       TS2445: Property 'thickness' is protected and only accessible within class 'StaveConnector' and its subclasses.
>       TS2445: Property 'x_shift' is protected and only accessible within class 'StaveConnector' and its subclasses.
>       TS2445: Property 'options' is protected and only accessible within class 'Stave' and its subclasses.
>       TS2445: Property 'font' is protected and only accessible within class 'TextBracket' and its subclasses.
>       TS2445: Property 'position' is protected and only accessible within class 'TextBracket' and its subclasses.
>       TS2445: Property 'start' is protected and only accessible within class 'TextBracket' and its subclasses.
>       TS2445: Property 'preFormatted' is protected and only accessible within class 'Tickable' and its subclasses.
>       TS2445: Property 'glyph' is protected and only accessible within class 'Note' and its subclasses.
> ```
> 
> @0xfe do you prefer to make these attributes public or to create accessors?

In the migration I found another protected attribute that is accessed `StringNumber.radius`

**Comment by rvilarl** [comment]
PianoPlay also working with OSMD

https://michaelecke.com/pianoplayts/

**Comment by mscuthbert** [comment]
My feeling is to make them public for 4.0 and we can make them protected in 5.0 with accessors.  But better at this point not to make more API changes in 4.0.

**Comment by ronyeh** [comment]
Sounds good! I'll send you all a new alpha build today with all of those properties made public again.
