### ISSUE TITLE
Tutorials directly in code.

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1218]
I would suggest to move the tutorials to a tutorials directoy in the source code and point to this directory in the wiki. With that we would make sure that they are mantained and do work. What do you think? I know that Ron agrees on that we have been discussing it in the past. @0xfe what do you think?

_Originally posted by @rvilarl in https://github.com/0xfe/vexflow/issues/1217#issuecomment-962633035_

**Comment by ronyeh** [comment]
I think they could all live inside the `docs/` folder. 

The wiki could remain as a bullet point list of links to appropriate example code and markdown docs. It can still contain user contributed snippets, but anything more complicated that a snippet that renders a 2 bar score to a div with id=boo should probably be in its own source file so it's more maintainable. Luckily GitHub makes source file easy to read with syntax highlighting, and permalinks to line numbers, etc. 

Our "users" are all software developers, so I believe they will appreciate having all tutorial and example code easily accessible via git clone of the main repo.

**Comment by rvilarl** [comment]
I am in the same line, I believe. Documentation generated with typedoc in `docs/` the tutorials in code in `tutorial/` or `demos/` this code should be executable and also link in the docs using markdown (ie.: `[[include:tutorial1.ts]`)

**Comment by ronyeh** [comment]
Right now, when we run grunt, the output of typedoc goes into `vexflow/build/docs/`.

I think the auto generated docs could remain in the build folder, since that folder is removed whenever we build. It would be slightly messier to put them in `vexflow/docs/` alongside any manually written markdown files.

I propose putting the tutorial and manually written documentation inside `vexflow/docs/`, and any self-contained running example code in `vexflow/demos/`. So the folder structure might look something like:

* `vexflow/docs/tutorial/README.md`
* `vexflow/docs/README.md`
* `vexflow/docs/typescript/README.md`
* ...

There are three files currenly in `vexflow/docs/`. Once Mohit decides if we want to proceed in this direction, we could move those three files into `vexflow/docs/legacy/`.

I do like how accessible a wiki is. However, I find it difficult to track what changes were made, and if the code even compiles or has typos. A vandal could always come in and delete a wiki page, and a maintainer would have to notice and revert the changes.

Keeping the official docs and tutorial in the main repo allows us to keep them versioned alongside the source code. (I know the wiki is technically in its own git repo, but it's not very obvious/visible to developers who git clone vexflow.)

We can always have a User Contributed Tutorials section on the wiki that is publishable by anyone at any time (just like today). And if any of those tutorials are great enough, we can include them in the official guides in the main repo.

Anyways, we should wait to see if @0xfe thinks this is a good idea.

**Comment by rvilarl** [comment]
I see your proposal goes further. I was just thinking about running tutorials in TS and referencing/including them within Vex.ts or Index.ts with mark down to get them in the typedoc documentation.

**Comment by 0xfe** [comment]
I like the notion about code reviewed and committed docs, but I'm trying to balance usability and overhead too. Docs are more for users than us developers, so trying to optimize for UX is more important to me than optimizing for ourselves.

Open to ideas, however the pattern on the front page of `vexflow.com` is ideal, IMO. (jsfiddle rendered tutorials, with editable code.)

**Comment by 0xfe** [comment]
To be clear, we can certainly have both -- and the tests do a great job of documenting the APIs too.
