### ISSUE TITLE
OSMD VexflowPatch: Stave

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1253]
prevent a bug where a modifier width is NaN, leading to a VexFlow error
stave.setSection(section, y, xOffset = 0, fontSize = 12):
add xOffset, fontSize arguments (see stavesection.js)

**Comment by sschmidTU** [comment]
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/899

**Comment by rvilarl** [comment]
@sschmidTU 
- could you try the problematic Score. TypeScript checks that NaN is not possible. This applies to `modifier.getPadding` and `modifier.getWidth`
- stave.SetSection. Why do you want to provide `xOffset` & `FontSize`?

**Comment by sschmidTU** [comment]
the NaN bug seems to be fixed in Vexflow 4, I checked with the score that caused it.
For `xOffset`, it's to avoid collisions, e.g. with metronome numbers. There are already a million optional offsets in Vexflow.
For `FontSize`, the vexflow default was 13, which was way too big for StaveSections in our view. This is again an optional value, which allows customizing their size.
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/919#issuecomment-768590973
