### ISSUE TITLE
Update developer documentation with new build instructions

### ISSUE THREAD

**Issue by 0xfe** [0xfe/vexflow#1271]
There have been lots of major changes to how VexFlow is built and developed (thanks @ronyeh!), and I'd like to make sure that our core developer documentation is up to date before we make more changes.

- [x] Update [Build and Release Instructions](https://github.com/0xfe/vexflow/wiki/Build%2C-Test%2C-Release).
- [x] Update [README.md](https://github.com/0xfe/vexflow/blob/master/README.md).
- [x] Update [Font Rendering](https://github.com/0xfe/vexflow/wiki/VexFlow-Font-Rendering) (if necessary.)
- [x] Add entry on ESM vs CommonJS to [FAQ](https://github.com/0xfe/vexflow/wiki/FAQ).
- [x] Reassign this bug to @0xfe to do an end-to-end test of instructions.

**Comment by ronyeh** [comment]
OK sounds good. I'll keep this thread updated as the tasks are completed.

**Comment by ronyeh** [comment]
I've been testing the workflow for releasing to NPM and GitHub in a somewhat automated way. I created a sample test project for this, and have written up some docs here:

https://github.com/ronyeh/simple-typescript-library/blob/main/docs/DevelopersGuide.md

The summary:
* Use the release-it npm package.
* After building and testing, run the following command:
```
GITHUB_TOKEN=__YOUR_PERSONAL_ACCESS_TOKEN__   npm run release
```

This requires getting a GitHub personal access token with **repo** permissions: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

* The release-it script will guide you through a series of Y/n questions. Press ENTER to accept the defaults or CTRL+C to abort. For example, it might look like this:
```
$> GITHUB_TOKEN=__YOUR_PERSONAL_ACCESS_TOKEN__   npm run release

> vexflow@4.0.1 release
> release-it

🚀 Let's release vexflow (currently at 4.0.0)

Empty changelog

? Select increment (next version): patch (4.0.1)
✔ echo add build/ folder
✔ git add -f build/
✔ git commit -m 'Add build/ for the release.'

Changeset:
 M package-lock.json
 M package.json

? Publish vexflow to npm? Yes
? Please enter OTP for npm: __YOUR_ONE_TIME_PASSWORD__
? Commit (release vexflow version 4.0.1)? Yes
? Tag (4.0.1)? Yes
? Push? Yes
? Create a release on GitHub (Release 4.0.1)? Yes
✔ echo Successfully released vexflow v4.0.1 to 0xfe/vexflow
✔ echo remove build/ folder
✔ git rm -r build/
✔ git commit -m 'Remove build/ after the release.'
🔗 https://www.npmjs.com/package/vexflow
🔗 https://github.com/0xfe/vexflow/releases/tag/4.0.1
🏁 Done (in 33s.)

```

**Does this workflow sound good? I will submit a PR with docs and the release-it script.**

Three more things:
A) I would propose moving the documentation into the main repository. Ping @rvilarl for his opinion on this matter. 
B) In the example release script above, I add the `build/` folder to the git repo just before releasing, and then I remove the `build/` folder just after releasing. This is optional but I think there are some benefits to committing the build files (as we did for 3.0.9).
C) Demos in the repository can be displayed via codesandbox.io.

## A - Documentation in the Repository vs Wiki?
In my sample project, I have the same document in both the repo and on the wiki.

repo: https://github.com/ronyeh/simple-typescript-library/blob/main/docs/DevelopersGuide.md

wiki: https://github.com/ronyeh/simple-typescript-library/wiki/Developer's-Guide

There are advantages either way.

The wiki can be edited by any GitHub user, so it's fast and easy.

The repo docs require a PR to update the official docs. This is slower, but maintainers can review updates to the official docs. We can keep the wiki available for any one-off user guides written by devs who want to share information. If the guide is good enough, we can promote it into the repo docs. (The dev can submit a PR.)

One cool benefit to the repo docs is GitHub provides a table of contents button, which is great for longer documents:

<img width="682" alt="Table of Contents" src="https://user-images.githubusercontent.com/239113/148177385-c8b2dea4-9987-4fb8-9e5d-af1911dc0dc0.png">

I personally find it difficult to work on any longer markdown document in the GitHub wiki interface. I would prefer if our official guides / docs were hosted directly in the repository itself. That way, I could use VS code to work on both the code and docs at the same time, and they would be less likely to get out of sync.

## B - Commit build/ folder during releases?
Our npm run get:releases script retrieves build files for any tagged release. For versions 3.0.9 and before, it pulls the release directly from the repository, since we used to keep the final release in `vexflow/release/`. However, in 4.x I removed the release/ folder and we now deploy to npm directly from the `build/` folder, which is usually empty (via .gitignore).

I propose committing the final release files into the repo **temporarily** so that when we tag a version (e.g., 4.0.2), that version will contain the build files. This allows the get:releases script to pull the build files directly from the repository. After the release is shipped to GitHub and NPM, the build/ folder is emptied out again.

Is this approach OK with you all?

## C - Demos on codesandbox vs jsfiddle

We have been using JSFiddle for many of our demos. I propose that we move our demos to codesandbox.io.

codesandbox.io has a feature which will create a demo from any github URL. So we could host the code for our demos directly in our repository.

For example, for this repository folder: 
https://github.com/ronyeh/simple-typescript-library/tree/main/demos/hello

We replace the `https://github.com` => `https://codesandbox.io/s/github` and then you end up with this demo page:

https://codesandbox.io/s/github/ronyeh/simple-typescript-library/tree/main/demos/hello

Of course they also support iframe embeds. The embed URL for the above page is:

https://codesandbox.io/embed/github/ronyeh/simple-typescript-library/tree/main/demos/hello?fontsize=14&hidenavigation=1&theme=dark


Anyways, those are some of my current thoughts!

**Comment by ronyeh** [comment]
Added some info on Common JS vs ESM here: https://github.com/0xfe/vexflow/wiki/VexFlow-4

**Comment by ronyeh** [comment]
I updated the README and added more wiki documentation (e.g., [VexFlow 4](https://github.com/0xfe/vexflow/wiki/VexFlow-4-Tutorial/). I'm sure there are bugs with the docs and I'll fix them as we discover them.

The docs reference CDN URLs that won't really work until VexFlow 4 is shipped.... :-)

What do you think? You can try shipping a RC, and then if the release script works as expected, we can ship the real thing.

Once 4.0.1 is out, I can update the JSFiddle examples to point to the 4.0.1 release.

**Comment by ronyeh** [comment]
To ship a **release candidate** from a fresh install:

```
mkdir vexflow
cd vexflow/
git clone git@github.com:0xfe/vexflow.git .
npm ci
grunt release:rc
```

To ship a full release, with an automated GitHub release, you'll need a GitHub personal access token. The command will look like:

```
GITHUB_TOKEN=XYZABC grunt release
```

See: https://github.com/0xfe/vexflow/wiki/Build,-Test,-Release#release-to-github-automatically

**Comment by 0xfe** [comment]
Thanks for carrying this whole thing, Ron!
