### ISSUE TITLE
Grace note position is affected by other modifiers / annotations

### ISSUE THREAD

**Issue by nitzanrh** [0xfe/vexflow#1295]
HI all,

I'm working on using Vexflow for creating some snare drum etudes. 
For some reason, the grace note's position changes if the "main" note has a modifier or annotation. 
This creates a lot of layout mess with snare drum etudes, where accents, grace notes (aka flams) and annotations (aka stickings) are used frequently.

Is this by design? is there a way to avoid this? (ie have all the grace notes in the same relative position to their "main" notes)

Check out fiddle:
https://jsfiddle.net/b681dk9r/ 

Cheers,
Nitzan

**Comment by rvilarl** [comment]
Hi Nitzan, Which version of vexflow are you using?

**Comment by AaronDavidNewman** [comment]
It is the newest.  Even using the font formatting doesn't help this.

The issue is that vertical modifiers like annotation and articulation report their width independently.  So the widths sum, even though they are on top of each other.

Ideally, if the annotation is centered, it would only report the width if it exceeded the current modifier context width.

**Comment by nitzanrh** [comment]
> It is the newest. Even using the font formatting doesn't help this.
> 
> The issue is that vertical modifiers like annotation and articulation report their width independently. So the widths sum, even though they are on top of each other.
> 
> Ideally, if the annotation is centered, it would only report the width if it exceeded the current modifier context width.

Hi Aaron,
Thanks for your reply.
Even disregarding the annotation, the accent itself displaces the grace note position by quite a bit. If the modifier is centered (above or below the note)  I don't see why it should affect the grace note position

**Comment by AaronDavidNewman** [comment]
> Even disregarding the annotation, the accent itself displaces the grace note position by quite a bit

This is a good observation.  This has been annoying me for a while, but I don't think I ever made the connection. 

Articulations and centered annotations should always subtract the note head width from their width, and only report the overlap (when there is a note head). Ornaments and other modifiers are a little harder because their formatting isn't always strictly vertical or horizontal.

I will take a crack at this since I have been messing with the vertical formatters, anyway.  I have a feeling this will have some unexpected consequences, but, only one way to find out.

This is how it looks in Smoosic, same issue

![image](https://user-images.githubusercontent.com/5438280/149630195-56eb4a7a-c547-4c8a-8a6a-6ae7954c908a.png)
![image](https://user-images.githubusercontent.com/5438280/149630206-827ebbc0-2cde-4c78-8d8d-45b690e0dcb2.png)

**Comment by nitzanrh** [comment]
Hi Aaron,

Sweet, thanks for looking into this.

While on the subject, here is another weird behavior with annotations:
https://jsfiddle.net/r3p45b97/3/

It seems to me that:
A. getMinTotalWidth is somewhat off (although I understand that is something the team is aware of)
B. Increasing the stave's width by the width of the annotation doesn't always makes sense, especially if the annotation already fits in the current width (stave3 in the fiddle)

**Comment by AaronDavidNewman** [comment]
For A, you probably want something like:

``` javascript
var stave1 = new VF.Stave(10, 10, width1 + VF.Stave.defaultPadding);
```

`getMinTotalWidth ` just gives you the width of all the stuff in the voice, e.g. the note + flag. 

Also, you are definitely using an old version of vexflow because `Stave.defaultPadding` is not defined.  Mine is up-to-date as of about 3 months ago, you could try that (you can also just add 15 pixels or so, which is what the value defaults to).

https://aarondavidnewman.github.io/vexflow_smoosic/releases/vexflow-debug.js

**Comment by nitzanrh** [comment]
I will give the VF.Stave.defaultPadding a shot, thanks :)

As for the version, I think it is the same as the one you sent.
Here is the same fiddle but with your attached vexflow-debug.js file:
https://jsfiddle.net/r3p45b97/5/
