### ISSUE TITLE
EasyScore.Draw_Accidentals Test - Visual Error

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1307]
Accidentals overlapping

![EasyScore Draw_Accidentals Bravura](https://user-images.githubusercontent.com/22865285/151691433-e3b938aa-bc09-43ed-8012-dd44d55bb602.png)

**Comment by rvilarl** [comment]
This one was fine in 3.0.9

![image](https://user-images.githubusercontent.com/22865285/151751508-a9aeac74-d1dc-4c9b-95b2-ba5ef280d25e.png)

**Comment by AaronDavidNewman** [comment]
It is more compressed because it uses preCalculateMinTotalWidth in EasyScore, if the staff width is not specified.  So the test case is changed, but I don't know if that is related to the bug.  This happens on the first note, and if the formatter were low on space, it would overflow on the right edge.  

If the staff width is set to the old level in 4.0, do we still see the collision?

**Comment by ronyeh** [comment]
[VexFlow 4](https://unpkg.com/vexflow@4.0.1-alpha.2/tests/flow.html#module=easyscore&filter=accidentals)

[VexFlow 3.0.9](https://unpkg.com/vexflow@4.0.1-alpha.2/tests/flow.html#module=easyscore&filter=accidentals&ver=unpkg@3.0.9)

Open the two links in separate tabs and flip between them to see the difference.

**Comment by AaronDavidNewman** [comment]
I need to see the new code with the old width.  I'll try to set it up later today.  Work is busy.

**Comment by AaronDavidNewman** [comment]
I see it now thanks Ron.  So this isn't really a regression, at least not of the formatting.   In the past the width of `system` came from here:

``` javascript
 const justifyWidth = this.options.noPadding
      ? this.options.width - this.options.x
      : this.options.width - (startX - this.options.x) - Stave.defaultPadding;
```
where the default options.width was 500px.  So it was hard coded, and if you hard-coded the same width now, it would look the same as 3.0.9.

Current change uses `preCalculateMinWidth` which is apparently undercounting in this case.  Maybe it isn't catching the fact that these accidentals can't be vertically aligned, because that isn't known until after formatting, and preCalculate... happens before that.  And since we expected visual regression to change, I missed that they were overlapping.
