### ISSUE TITLE
Articulation Articulation___Inline_Multiple Test - Visual Error

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1309]
Articulations overlapping notes

![Articulation Articulation___Inline_Multiple Bravura](https://user-images.githubusercontent.com/22865285/151691662-2ffb5212-227d-475b-9da7-f0f302521b7b.png)

**Comment by 0xfe** [comment]
This is a regression.

**Comment by rvilarl** [comment]
This one was almost fine (one dot is overlapping) in 3.0.9

![image](https://user-images.githubusercontent.com/22865285/151750843-e6e426fa-3e43-4e48-87aa-351b1dfdc8f5.png)

@AaronDavidNewman could you look into this one?

**Comment by sschmidTU** [comment]
Is this maybe a regression of #1267 or other recent y formatting changes?

**Comment by AaronDavidNewman** [comment]
This is possibly vertical placement of articulations, which was touched recently.  Strange that the visual regression tests didn't pick this up.  I've noticed that changes that mostly affect horizontal lines tend not to...

**Comment by AaronDavidNewman** [comment]
Probably the issue is that the logic doesn't consider the number of lines in the beam.  If the lines in beam are _n_ , it should add n-1 or n lines (depending on line or space) either up or down, if the existing line is 0 (meaning, it is the first modifier vertically either up or down).  It looks like it should do this regardless of the stem direction.  This is in `articulation.format`.  I'll probably have time to look at this later in the week.
