### ISSUE TITLE
Multiple rests - how to render

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1331]
@sschmidTU reported in https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1139

> * [ ]  Unnecessary double rest in test_rest_positioniong_simple_g_eighth
>   ![image](https://user-images.githubusercontent.com/33069673/153039068-741dfadf-1330-4ae8-a2ae-ffdf645604fc.png)

@mscuthbert  @AaronDavidNewman should we only draw one rest in this situation above? If yes, should that also apply to the vexflow test below?

![Three_Voice_Rests Auto_Adjust_Rest_Positions___Three_Voices__1 Bravura](https://user-images.githubusercontent.com/22865285/155271729-20f1afef-2858-4027-ad51-c84c0db08c5e.png)
n

**Comment by 0xfe** [comment]
I think that example needs better vertical centering, but don't we need both rests there (for the general case)? Otherwise we're introducing ambiguity in the relationships across the voices.

**Comment by sschmidTU** [comment]
My intuition was that you can combine the rests if it's obvious that they're shared by both/all voices.

I found this discussion on musescore:
https://musescore.org/en/node/34511
> page 528 of Gould's 'Behind Bars':
"Separately stemmed parts share rests wherever possible."
Other layout books I have all say the same thing. On page 12 of 'Preparing Traditional Music Manuscript' Second Edition by Michael Mohn:
"Do not double rests in split-stem parts if the rhythm is obvious."

Marc Sabatella argues there are some cases where you don't want to unify the rests, though he isn't very specific as to what those might be, and I disagree with him that this is not a good default. I think this should be the default, and maybe you should have an option to disable it.
But in any case, even Marc seems to agree that unifying is correct if there are no 3rd or 4th voices, which seems like 99% of the time. So if we want to be completely correct, we can just unify if there are less than 3 voices.

**Comment by AaronDavidNewman** [comment]
I think there are different use cases, and it might be hard to tell what is 'obvious' from the perspective of vexflow.

If they are 2 voices of a single part, you would want to combine the rests if you can.  if they represent 2 different parts, often you would show them separately since the musicians will be expecting 2 lines, and will want to find 'their' line.

Maybe the rule should be that we combine them if they would otherwise overlap?  In that case, even if there are 2 independent lines, it should be easy enough to read.

In Smoosic we just handle this by letting the user hide any rests (by making them transparent).

**Comment by sschmidTU** [comment]
> if they represent 2 different parts, often you would show them separately since the musicians will be expecting 2 lines, and will want to find 'their' line.

I've seen this argument and I understand it, though I still think even there a single rest is very readable, maybe even preferable. Double rests in any case are very ugly if looking at the score wholistically.

**Comment by AaronDavidNewman** [comment]
I've decided I have no knowledge of what is best here.  The blessed example def. looks better, but that's kind of a strange example.

**Comment by rvilarl** [comment]
Thanks @AaronDavidNewman I also don't.
@mscuthbert perhaps you can ask your friend. The professional engraver.

**Comment by rvilarl** [comment]
@mscuthbert please do not forget this one :)

**Comment by mscuthbert** [comment]
The blessed version of the last image is correct for the quarter rest and half rest.  However, the eighth rest only makes sense if it is placed below the staff (i.e., within the stem-down voice's "realm of operation").  Otherwise it looks to the player reading the upstemmed notes that she is to play a quarter note and then rest for an eighth note, quarter, and half note.

For the somewhat contrived three-voices on a staff example, I would consolidate any time all three voices have a rest, or the top two voices or the bottom two voices have a rest, but not when top and bottom rest simultaneously.  (But I would never try to write this passage on a single staff...)
