### ISSUE TITLE
Formatter is ignoring the length of the last note.

### ISSUE THREAD

**Issue by RyoSusami** [0xfe/vexflow#1335]
The formatter seems to ignore the length of the last note.

Ver.3.0.9
https://jsfiddle.net/tzp5m2qc/1/
![image](https://user-images.githubusercontent.com/36094352/155961034-098114a3-ad76-4391-86cd-786ae915ec97.png)

Ver.4.0.0 (It behaves the same in ver.4.0.1-beta.2)
https://jsfiddle.net/tzp5m2qc/2/
![image](https://user-images.githubusercontent.com/36094352/155961101-7241e835-9a72-4481-84c5-1349e3d11bf4.png)

Even if I change softmaxFactor, it doesn't seem to be adjusted like 3.0.9.
(Or is it necessary to make additional settings in Ver.4?)

**Comment by AaronDavidNewman** [comment]
The current behavior of the formatter is to use the full measure width by default.  Because usually you don't want all the space at the end of the measure.  If you are sight-reading , there would be a big gap before the next measure that would be hard to track. And at the very least, it wastes a lot of space in an empty score.

You can format the notes and measure separately if you want that.  You can get the min note width using this function, and then pad to taste:

``` javascript
const width = formatter.preCalculateMinTotalWidth([voice]);
formatter.format([voice], width + 100);
let stave = new VF.Stave(20, 20, 300);
```

Here is a fiddle you can play around with.

https://jsfiddle.net/e2zrbuaj/

**Comment by rvilarl** [comment]
@AaronDavidNewman is there any direction in Behind Bars in this regards?

**Comment by AaronDavidNewman** [comment]
> is there any direction in Behind Bars in this regards?

sure there's a whole section on rhythmic formatting.  The right bar should be where the next note would be, or a little closer.  The 3.0.9 example has the right bar about 5 times further away than it should be.

**Comment by RyoSusami** [comment]
@AaronDavidNewman Thank you for your advice. Consider inserting padding manually using .preCalculateMinTotalWidth () etc.

In my opinion, it seems strange that the current behavior is the default and requires manual control to apply the note length.

**Comment by RyoSusami** [comment]
Maybe it's already been considered, but for reference...

According to the description of P39-40 Rhythmic spacing in "Behind Bars",

> Musicians rely heavily on good spacing to read rhythm, Poor horizontal spacing is often the main problem of badly presented music and hinders the reading of it.

**Comment by AaronDavidNewman** [comment]
The current logic is to allow min right padding of between 1 and 1/2 of the 'ideal' distance, based on the note width.  You could reduce this tolerance to something like 1 and 2/3.  In formatter.ts, line 740 or so:

``` javascript
    const calcMinDistance = (targetWidth: number, distances: Distance[]) => {
      let mdCalc = targetWidth / 2; // try 1.5 here
      if (distances.length > 1) {
        for (let di = 1; di < distances.length; ++di) {
          mdCalc = Math.min(distances[di].expectedDistance / 2, mdCalc);  // 1.5 here also
        }
      }
      return mdCalc;
    };
```

Submit a PR if you find this more pleasing.  Most of our use cases are around handling tight spacing, not so many about too much horizontal spacing.

2.0 (original):
![image](https://user-images.githubusercontent.com/5438280/156404991-0dadbe30-ceec-406c-9309-b06646c174f3.png)

1.5:
![image](https://user-images.githubusercontent.com/5438280/156404473-1e70ac7f-d88e-467b-a207-78ed521b7eed.png)

**Comment by mscuthbert** [comment]
The version 3 spacing isn't correct to my eyes, but the v4 is far less good.  In no case should have half note have between it and the first note of the following measure less space than between two adjacent quarter notes.  [ it's the space to the first tick in the following measure (assuming no start-modifiers like a clef/key/time change) that matters if there is a following measure on the same system, not necessarily the space to the barline. ]

The target_width 1.5 looks better than the 2.0 -- but would need to see it in context.  I think that no matter what though this 2 or 1.5 number should be a configurable constant on the Formatter object, avoiding the magic number in the code and allowing users to modify it without changing the code.

(Thanks all!)

**Comment by AaronDavidNewman** [comment]
> In no case should have half note have between it and the first note of the following measure less space than between two adjacent quarter notes

If that's the case, then this calculation is probably wrong altogether.  We calculate the right padding based on the min space between the notes, not by the ideal spacing between the last note and the end of the bar.  The problem happens when the last note is the longest, because the last note is never 'between' anything.

**Comment by mscuthbert** [comment]
I should say, "in no normal/ideal case" for "in no case" above.  Obviously, if you have a narrow measure, and put in the same Qtr Qtr Half case above, but add a 27-grace-note element before the second quarter, then all bets are off.

**Comment by RyoSusami** [comment]
Thank you everyone for considering this matter.

If the division parameter of targetWidth becomes configurable, I haven't tried various patterns yet, but in my case, I adjust the division parameter from 1.0 to 1.2 and softmaxFactor from 10 to 30.

I think it is better to consider the existing users when deciding the default value of the division parameter.

**Comment by ronyeh** [comment]
Hi all, is this something that needs to be addressed before we release 4.0 (i.e., is the workaround to increase the width of the measure)? Or can we wait until the next release, 4.1?

My intuition says that a measure containing a [quarter, quarter, half note] should _try its best_ to give 1/4 of the free space to each of the quarter notes, and 1/2 of the free space to the half note. I define the "free space" as empty area between the time signature and the bar line.

**Comment by AaronDavidNewman** [comment]
> is this something that needs to be addressed before we release 4.0 

It depends on your timeline.  We could fix it soon.  I should be able to push a PR today, but I may need some more time to verify the visual diffs.  If there are lots of diffs we may want to hold off.

@RyoSusami was correct when he said we weren't considering the width of the last note.  The right-most note is placed relative to other notes.   My fix is to make the right padding based on the width of the last tickable in the measure.  If it overlaps the padding, we recalculate with a lesser width.

With my fix it the original case looks like this.  This still looks like a lot of space to me, but maybe that's just because the measure is so long.

![image](https://user-images.githubusercontent.com/5438280/156615593-617706b1-63a5-464e-87c2-afb3344616c7.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman I can help looking at diffs. Just make a PR and leave as draft until we check

**Comment by AaronDavidNewman** [comment]
@rvilarl thank man.  https://github.com/0xfe/vexflow/pull/1339

**Comment by RyoSusami** [comment]
Thank you everyone, and thank you positive improvement @AaronDavidNewman !
