### ISSUE TITLE
OSMD: Grace note colliding

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1363]
> * [ ]  Grace note colliding in test_clef_end_measure (measure 1)
>   ![image](https://user-images.githubusercontent.com/33069673/153038008-0b33ccc1-3f29-46d6-a057-15948e72c9f2.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman could you help me with that?
What is missing in the width calculation? I would say that `preCalculateMinTotalWidth` is not working properly with grace notes

https://jsfiddle.net/Ljyqndst/

**Comment by AaronDavidNewman** [comment]
You need to call 'joinVoices' before you call the preCalculateMinTotalWidth, otherwise the modifier contexts don't exist.  Then use the same formatter to format the voices.  This will save you from creating the modifier and tick contexts twice.

``` typescript
const formatter = factory
  .Formatter()
  .joinVoices(voicesArr);

staveWidth = formatter.preCalculateMinTotalWidth(voicesArr) +
    staves.get(1).getNoteStartX() -
    staves.get(1).getX() +
    VF.Stave.defaultPadding;
```
![image](https://user-images.githubusercontent.com/5438280/163588458-cb03886d-0bd4-4952-98c4-4ff17b364635.png)

**Comment by rvilarl** [comment]
> You need to call 'joinVoices' before you call the preCalculateMinTotalWidth, otherwise the modifier contexts don't exist. ALso, until you do that, you don't know which voices are to be formatted together.

@AaronDavidNewman Thanks a lot! As a minimum we should document this requirement :)

**Comment by rvilarl** [comment]
@AaronDavidNewman I modified that the jsfiddle and it looks much better but the grace notes are colliding. I must still have a bug. Any tip?

https://jsfiddle.net/xw27b9ue/
![image](https://user-images.githubusercontent.com/22865285/163608799-1f9a93ce-6ba5-4c18-98ce-311f1926fbd5.png)

**Comment by AaronDavidNewman** [comment]
It looks like we are not using any left padding for the grace notes.  I don't think this is because there isn't enough room, but I can't be sure without digging in some more.  If you add a few more pixels to the value returned by preCalculate...it looks OK.  Remember that preCalculate.. is a 'min' width.

It doesn't really make sense to add the start X to the formatting width of the voice.  Any padding you add is distributed evenly across the notes (according to the formatting logic).  Add additional padding for start/end when you create the staff.  See the formatting_tests case called `multiStaves`.

**Comment by rvilarl** [comment]
> ```ts
> const formatter = factory
>   .Formatter()
>   .joinVoices(voicesArr);
> 
> staveWidth = formatter.preCalculateMinTotalWidth(voicesArr) +
>     staves.get(1).getNoteStartX() -
>     staves.get(1).getX() +
>     VF.Stave.defaultPadding;
> 
> formatter
>   .format(
>     voicesArr,
> ...
> ```

@AaronDavidNewman I have changed the way to call formatter and I am getting another issue, the notes on the third measure are not aligned between staves. Any tip? And thanks a lot.

https://jsfiddle.net/17Lq5e63/

**Comment by rvilarl** [comment]
> It looks like we are not using any left padding for the grace notes. I don't think this is because there isn't enough room, but I can't be sure without digging in some more. If you add a few more pixels to the value returned by preCalculate...it looks OK. Remember that preCalculate.. is a 'min' width.

but I would say that in a minimum arrangement we could leave less space between the note and its grace notes and more space between the grace notes and the preceeding note. Don´t you agree?
 
> It doesn't really make sense to add the start X to the formatting width of the voice. Any padding you add is distributed evenly across the notes (according to the formatting logic). Add additional padding for start/end when you create the staff. See the formatting_tests case called `multiStaves`.

I copied the usage of start X from `System`

**Comment by rvilarl** [comment]
> It looks like we are not using any left padding for the grace notes. I don't think this is because there isn't enough room, but I can't be sure without digging in some more. If you add a few more pixels to the value returned by preCalculate...it looks OK. Remember that preCalculate.. is a 'min' width.

@AaronDavidNewman will you dig into this one adding some extra room is not optimal because it depends on many parameters like the number of notes for example
