### ISSUE TITLE
OSMD: Slur arc too high

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1367]
> * [ ]  Slur Arc too high in test_slurs_long_steep_arc
>   ![image](https://user-images.githubusercontent.com/33069673/153039217-82a0281e-daa7-4464-adf6-dd806b9ee669.png)

**Comment by sschmidTU** [comment]
This issue is almost purely a problem in OSMD, where the slur arc is calculated.
It's just strange that the arc got steeper just by updating to vexflow 4.

(for reference: [my original list of OSMD vexflow 4 transition issues](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1139#issuecomment-1032827943))

**Comment by rvilarl** [comment]
OSMD problem
