### ISSUE TITLE
OSMD: Measure way too far

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1370]
> * [ ]  Often the last notes in a measure are way too far from the measure line (except for rare cases):
>   before:
>   ![image](https://user-images.githubusercontent.com/33069673/160667290-05be91db-96f1-4a3b-99b7-24b967ae49c1.png)
> 
> after: ![image](https://user-images.githubusercontent.com/33069673/160667320-531aa967-722c-45df-8d02-765b5dc4ff5f.png)
> 
> (`test_rest_positioning_note_overlap_1st_voice_chord.musicxml`)
> 
> before: ![image](https://user-images.githubusercontent.com/33069673/160667532-2a1febeb-5c03-4109-a7ce-1a51827a2f77.png)
> 
> after: ![image](https://user-images.githubusercontent.com/33069673/160667573-aa0d1750-5ebb-47a4-a3d7-ac19fc9599e6.png)
> 
> (OSMD Function Test - Chord Symbols. Also in OSMD Function Test - Color, etc)

**Comment by rvilarl** [comment]
@sschmidTU I want to use the test files in OSMD to produce tests for VexFlow. Is there any problem with the license of OSMD not being MIT?

**Comment by sschmidTU** [comment]
@rvilarl You can use the OSMD test files, they aren't full pieces of music that are protected by copyright.

**Comment by rvilarl** [comment]
@AaronDavidNewman I have produced some jsfiddles to show the behaviour

for the first score,
https://jsfiddle.net/wempuknj/
**with `width`:**
![image](https://user-images.githubusercontent.com/22865285/162374818-526b0dac-3244-4253-a89e-334789c71630.png)

**without `width`:**
https://jsfiddle.net/wempuknj/1/
![image](https://user-images.githubusercontent.com/22865285/162375010-1567b615-74bd-404c-81dd-3f52795e761e.png)

It seems that providing a `width` causes the problem. The rests also overlap with the notes although `align_rests` is `true`

**Comment by AaronDavidNewman** [comment]
These are good examples!

I see the problem when the right padding is too wide.  We are considering the distance between the note and the right bar in the padding, but we need to also consider the distance to the previous tick context.

It doesn't have to do with measure width specifically, except the too-big gaps are smaller if there is less space.  It doesn't really have to do with softmax factor either.  In this case, it is a 2/4 measure so both 1/4 notes have the same allotted space no matter what the value is.

Gonna be out of town this weekend, should be able to look at it on Monday.

**Comment by AaronDavidNewman** [comment]
I was wrong in my last post.  The issue here is the softmax factor.  At 100, the formatter has the 1/8 taking up 20% of the measure, vs. 60% for the 1/4 note.  So the last 1/4 note is already well past the ideal distance from the previous note.  At 2, the 1/4 note takes up 37% and the 1/8 takes up 30%.

100:
![image](https://user-images.githubusercontent.com/5438280/163092158-4ae991be-047c-485b-96e1-4c0f7c2162f3.png)

20:
![image](https://user-images.githubusercontent.com/5438280/163092202-1d12c71c-eee3-49e3-a522-441290b9f87f.png)

5:
![image](https://user-images.githubusercontent.com/5438280/163092239-d215e379-5d19-42b6-bf59-a9ffd368bdb7.png)

2:
![image](https://user-images.githubusercontent.com/5438280/163092431-f0227f49-eeed-492a-92f9-0086b29bb84b.png)

Y'all can play around with this fiddle and set softmax to different things.

**Comment by rvilarl** [comment]
Should we change the default to 5?

btw @AaronDavidNewman did you see my question above?
> @AaronDavidNewman @0xfe I tried to use factory directly and now the rests heavily overlap, do you know what I am missing ?
> 
> https://jsfiddle.net/08x9c4n1/

**Comment by AaronDavidNewman** [comment]
> The softmax does not seem to play a role on the other example though

Sure it does, but I don't quite understand what you're looking at in that example.  Where is the formatting not correct?

> I tried to use factory directly and now the rests heavily overlap

are you talking about the vertical overlap?  Rests are just notes, not modifiers.  You can place them wherever you want.
``` javascript
note = score.notes('C4/8/r', { clef: 'bass' })[0];
```

![image](https://user-images.githubusercontent.com/5438280/163594459-262cabde-8c73-42d7-829b-b808e43644c5.png)

**Comment by rvilarl** [comment]
> > The softmax does not seem to play a role on the other example though
> 
> Sure it does, but I don't quite understand what you're looking at in that example. Where is the formatting not correct?
I was seeing if there was a difference with softmax. There is no error here but it does not look good in OSMD. I am trying to investigate why
 see https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1139
> 
> > I tried to use factory directly and now the rests heavily overlap
> 
> are you talking about the vertical overlap? Rests are just notes, not modifiers. You can place them wherever you want. Edit: Sorry, I see there is an align_rests option. I don't use that in Smoosic. So I'm not sure what's going on there. It doesn't look like that code has changed, though. More edit: It looks like align_rests doesn't do what you think it does. It aligns vertically with the next note in the same voice, it does not try to avoid a collision with other voices in the same stave. I don't know if this is new behavior.

Thanks for the explanation about align_rest :)

**Comment by AaronDavidNewman** [comment]
>There is no error here but it does not look good in OSMD. I am trying to investigate why

Maybe it has to do with the lyrics?  If you are using annotate, that behavior has changed.  And there is still a bug with chord changes and how much horizontal space they take up (too much)

**Comment by rvilarl** [comment]
@sschmidTU the OSMD issues above are no issues they are the result of taking into account the duration of the last note.

**Comment by sschmidTU** [comment]
@rvilarl Not sure what you mean, but the "before" versions in the first post are issues. The last notes in the measure are way too far from the measure end, you will never find this appearance in any printed score, it looks very wrong.

**Comment by rvilarl** [comment]
> >   before:
> >   ![image](https://user-images.githubusercontent.com/33069673/160667290-05be91db-96f1-4a3b-99b7-24b967ae49c1.png)
> > 
> > after: ![image](https://user-images.githubusercontent.com/33069673/160667320-531aa967-722c-45df-8d02-765b5dc4ff5f.png)

@sschmidTU I mean that the location within the stave must be prportional to note duration. There was a bug in VexFlow not taking into account the duration of the last note. In this 2 quarter staff the second quarter of each voice should be more or less in the middle and that was fixed. @AaronDavidNewman is that right?

**Comment by AaronDavidNewman** [comment]
I've lost track of 'before and after'.  The right bracket should be roughly the same length or slightly smaller than the left bracket here, that is the rule that should apply to this test case. 

Too long:
![image](https://user-images.githubusercontent.com/5438280/165632663-1bc4a7ac-b924-475c-9534-02207e2663e6.png)

Too short (earlier 4.0 vexflow with right-justified last note):
![image](https://user-images.githubusercontent.com/5438280/165632756-8a519363-fea2-43dd-8a37-1d277e7bdd52.png)

Just right?
![image](https://user-images.githubusercontent.com/5438280/165632902-1cca29c3-b607-484a-ae70-c2491ba1e9cc.png)

**Comment by sschmidTU** [comment]
Ah yes, this looks to be quite good with softmax 5. Thanks for the info!

I initially thought there was still way too much room to the measure end, but it looks like Musescore is rendering it almost the same:

<img width="243" alt="image" src="https://user-images.githubusercontent.com/33069673/165633964-677de1f3-9339-4c89-bf44-b3f4fc3fce7e.png">

musicxml:
[test_rest_positioning_note_overlap_1st_voice_chord.txt](https://github.com/0xfe/vexflow/files/8577909/test_rest_positioning_note_overlap_1st_voice_chord.txt)

In some cases in traditional scores the notes do seem to be slightly closer to the measure end, here is the end of Brahms - Hungarian Dance No. 5, also in 2/4:
![image](https://user-images.githubusercontent.com/33069673/165634682-3541b6d5-d3d6-402c-bb40-dc9bee0690d0.png)

Maybe the rest of the measure just gets shortened to save space.
Also, it's a little bit easier to read when you're performing, because you want to know what the next note to play is, you don't need a lot of empty space.

But this seems to be a rather small optimization now, so I'd say the core issue is fine now.
