### ISSUE TITLE
MusicXML test suite: formating issues leading to overlaps

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1381]
we are progressing with the Unofficial MusicXML test suite and test 32a is revealing several formatting issues.

Here is the jsfiddle for 32a

https://jsfiddle.net/L1c0gz86/1/
![image](https://user-images.githubusercontent.com/22865285/164618833-e9142c92-6db3-4cd5-83d3-10d301c95617.png)

Here the reference

https://lilypond.org/doc/v2.20/input/regression/musicxml/collated-files#t_g32-_002e_002e_002e-notations-and-articulations

**Comment by rvilarl** [comment]
@AaronDavidNewman Thanks! I have also set 'scoop' to left and they worked well but setting chords they still overlap

https://jsfiddle.net/fbu15gor/

My observations:
- format does not allow enough space for 'scoop', 'doit', 'fall', 'tr', 'turn', 'turn_inverted', 'mordent' & 'mordent_inverted'
- `factory` is missing an `Ornament` function.

**Comment by AaronDavidNewman** [comment]
@rvilarl I added factory to ornament in [this pr](https://github.com/0xfe/vexflow/pull/1382)
I also address the width issues for some of the jazz ornaments.  For Mordant, I believe this is intentional because the mordant usually floats above the staff and off to the right of the note.  So it doesn't not affect the width of the note.  Ornaments are harder to format than articulations since the don't always just go above the note, and might needs some help from the host application.

**Comment by rvilarl** [comment]
@AaronDavidNewman will you look into the overlaps?

**Comment by rvilarl** [comment]
@AaronDavidNewman  here a jsfiddle update with 4.0.3, I do not know if 4.1 has changes related to this one.

https://jsfiddle.net/azdr2w9n/

**Comment by AaronDavidNewman** [comment]
@rvilarl  I don't think it has changed because 4.1 version looks the same with that fiddle.  But I don't know why the jazz articulations aren't working there.  Here is the same measure 6 in smoosic, running the same vexflow code.  It doesn't seem like the factory is honoring your requested placement:

![image](https://user-images.githubusercontent.com/5438280/177337936-292fef69-ef30-409d-abcc-5a02c875f99d.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman will you submittiert a PR?

**Comment by AaronDavidNewman** [comment]
Sorry I was wrong about cause.  I don't think there is a bug here.  For the jazz ornaments, you don't specify the position because the ornament determines that.   A fall always follows the note, so if you position to the right, it ends up being to the right even of that, far from the note.  You can just use the default position.

``` typescript
note = factory
  .StaveNote({ auto_stem: true, clef: 'treble', keys: ['C/5'], duration: '4' })
  .setStave(staves.get(1));
notes.push(note);
notes[notes.length - 1].addModifier(
  factoryOrnament(factory, { type: 'doit' }),
  0
);
note = factory
  .StaveNote({ auto_stem: true, clef: 'treble', keys: ['C/5'], duration: '4' })
  .setStave(staves.get(1));
notes.push(note);
notes[notes.length - 1].addModifier(
  factoryOrnament(factory, { type: 'fall' }),
  0
);
```

![image](https://user-images.githubusercontent.com/5438280/177600293-a05d2596-c8c6-4703-87ed-e2db02aaef55.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman I have looked into this topic and I think that there is a bug. II believ, that these ornaments are indeed modifiers and should use the modifiers' infrastructure to coordinate their location with other modifiers rather than using the me trics file to calculate their position. I will make a PR.

**Comment by AaronDavidNewman** [comment]
>  that these ornaments are indeed modifiers and should use the modifiers' infrastructure 

They do use the modifier infrastructure.  This is how it is able to avoid the dot in the image below:

![image](https://user-images.githubusercontent.com/5438280/178072881-35d9ffdb-e7d3-435f-b380-029591230bbd.png)

It might make sense to have some jazz ornaments ignore position parameter, since it doesn't do the expected thing - the position is baked into the symbol.

I think the only reason your symbols are colliding is because there's not enough room in the measure to accommodate the placement.

**Comment by rvilarl** [comment]
@AaronDavidNewman `Dot` is setting a position within the constructor:
```js
  constructor() {
    super();

    this.position = Modifier.Position.RIGHT;

    this.radius = 2;
    this.setWidth(5);
    this.dot_shiftY = 0;
  }
```
however `Ornament` is not doing that. I believe that we should add code like:
```js
if (Ornament.ornamentRelease.indexOf(type) >= 0) {
  this.position = ModifierPosition.RIGHT;
} else if ...
```
and reduce the values of `xOffset` in the associated metrics.

**Comment by AaronDavidNewman** [comment]
OK, if you think this is more clear.   Modifier.Position is problematic because it only indicates position in one direction.  Some ornaments are both above and right, for instance, and there's no way to notate that with a single value.  This is why the jazz ornaments specifically ignore that parameter in the formatter loops.  But the draw loop uses note.getModifierStartXY() which does not ignore position, and that's why we need the compensation in the metrics.

And you may run into problems because position is settable parameter - if you change the metric and use right formatting, you will break existing code that use the default position.
