### ISSUE TITLE
How to add dashes between syllables? And an how to add an underscore when one word has two notes?

### ISSUE THREAD

**Issue by stefanvonk** [0xfe/vexflow#1410]
Can someone help me with adding dashes between syllables correctly? I now add them as text after a space in the same TextNote as the syllable. I couldn't find it, but maybe there is a better way to do this? It would be very nice if it will also solve my problem with the margin besides syllables, as you can see in the screenshot below.

Besides that, what is the approach for adding the underscore when one word has two notes? Now I add the underscore as text in a TextNote, but maybe there is a better way to do this as well? 

![image](https://user-images.githubusercontent.com/5812312/174146548-502966c2-dc1d-40e7-b127-269d87cad84f.png)

Very appreciated if someone could help me out!

**Comment by AaronDavidNewman** [comment]
> I now add them as text after a space in the same TextNote as the syllable. I couldn't find it, but maybe there is a better way to do this? 

Not in vexflow, and I don't think the library can always guess where it should go due to different measures, different lines etc.  So it is probably best done in the application.  In [Smoosic](https://github.com/AaronDavidNewman/Smoosic) I manually place an svg text element between between the notes if the word ends in a hyphen, In the case of same word, 2 notes  I manually draw a line using svg line element under the second note.  And I always render the text itself without the '-'.

I use Annotations to do the lyrics themselves.  There are some examples of this in the vexflow test programs.

I hope that helps!  Also you can use Smoosic library itself to create music with lyrics and let it draw the hyphens for you :)

![image](https://user-images.githubusercontent.com/5438280/174155850-d82bf981-5d87-4fc5-99ed-566b52249458.png)

![image](https://user-images.githubusercontent.com/5438280/174155912-d460d2f6-1704-43ba-af83-726db71fa96d.png)

**Comment by stefanvonk** [comment]
Many thanks for your answer! Currently I add my lyrics with annotations in stead of TextNotes, its a lot better. Thanks!

The last question I have right now is, how can I place the dashes and underscores in a good way on the right place within the svg? Do you have an example for me?

**Comment by rvilarl** [comment]
@stefanvonk can you provide a jsfiddle to see how you are doing it

**Comment by AaronDavidNewman** [comment]
Here is the dash code from smoosic.  This is not very clean:

* `lyric.logicalBox` is the SVG bounding box of the lyric, however you get that. 
* `parent` is the group element of the lyric.  But it could be appended anywhere in the DOM, even the root element.  I just put it near the lyric for easy debugging.
* I always draw the line 1/2 the length of the preceeding lyric, no idea if that's good or not.

``` typescript

          const line = document.createElementNS(SvgHelpers.namespace, 'line');
          const ymax = Math.round(lyric.logicalBox.y + lyric.logicalBox.height / 2);
          const offset = Math.round(lyric.logicalBox.width / 2);
          line.setAttributeNS('', 'x1', (lyric.logicalBox.x - offset).toString());
          line.setAttributeNS('', 'y1', ymax.toString());
          line.setAttributeNS('', 'x2', (lyric.logicalBox.x + lyric.logicalBox.width + offset).toString());
          line.setAttributeNS('', 'y2', ymax.toString());
          line.setAttributeNS('', 'stroke-width', '1');
          line.setAttributeNS('', 'fill', 'none');
          line.setAttributeNS('', 'stroke', '#999999');
          parent.appendChild(line);

```

**Comment by stefanvonk** [comment]
Much appreciated! With your input I fixed it:

![image](https://user-images.githubusercontent.com/5812312/177003473-25399a70-802e-4d52-be54-a10f4e346434.png)

Thanks!
