### ISSUE TITLE
How to use multiple Systems with autowidth?

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1411]
In the tests there are examples using autowidth with one system but the examples with several systems use a fixed width (like bach_test). Is there a way to use it with several systems? How should the x of the following system be adjusted using autowidth on the previous one?

**Comment by AaronDavidNewman** [comment]
The Bach tests are actually a single system with multiple staves.  So you could use autowidth there, but the staves wouldn't justify on the right (maybe that's what you mean by multiple staves).

I think any application that has many systems on many lines and wants to format them to align vertically must use its own width estimation and manually set the widths of the staves.  Because sometimes a line wraps, and that affects all the measures on that line (they are widened to justify), plus the measure width now has to be recalculated with starting symbols (key signature).  That is what Smoosic does, and I'm sure OSMD must do something similar.

For a performant application, you can't even use the vexflow formatter for estimation - it is too slow.  Because it requires all the Vex notes, staves etc to exist, with their glyphs.  If you need to then adjust the width or add/remove symbols because a line wraps, you need to throw all that away and start over.  Maybe OSMD can get away with it since it only renders the music a single time.  But Smoosic tries to do it in real time (and still fails sometimes, because it is still running in a browser).

**Comment by rvilarl** [comment]
@AaronDavidNewman yes the bach score is a single system with multiple staves. However, the implementation is making a new system for each meassure. See `appendSystem` in bach_test which uses a fixed `width`. My question is would it be possible to implement that without providing the `width`?

**Comment by AaronDavidNewman** [comment]
>  My question is would it be possible to implement that without providing the width?

Right, and the answer is yes but there would be no way to justify on the right if you did that.   If you change bach_tests like so, it sort of works but you need to add some logic for the curves and system braces to get it to look good.

``` javascript
  function appendSystem() {
    const system = f.System({ x, y, autoWidth: true, spaceBetweenStaves: 10 });
    return system;
  }
  function drawSystem(system: System) {
    system.format();
    const stave = f.getStave();
    f.draw();
    if (stave) {
      x += stave.getWidth();
      if (x > 900) {
        y += 230;
        x = 20;
      }
    }
  }

```

![image](https://user-images.githubusercontent.com/5438280/174449421-2c583dd9-fba1-4880-81ac-866927acf046.png)

**Comment by rvilarl** [comment]
Thanks
