### ISSUE TITLE
Ratioed tuplets doesn't show dots

### ISSUE THREAD

**Issue by nitzanrh** [0xfe/vexflow#1439]
Hi all,

As the title suggests, I'm trying to draw some basic tuplets with brackets and ratio, however when I set ratioed to true it draws the ratio without the dots(ie 3 2 instead of 3:2)

Here's a basic fiddle based on Ronyeh's tuplets tutorial

https://jsfiddle.net/01ned978/

Cheers,
Nitzan

**Comment by rvilarl** [comment]
@nitzanrh thank you for reporting the bug.

**Comment by rvilarl** [comment]
It seems that this is only working properly with canvas

![image](https://user-images.githubusercontent.com/22865285/191099239-1c0a3c62-69e1-493b-ab66-162e69796b99.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman could you look into that? I do not figure out why ctx.arc(...) ctx.fill() is not working here within the tuplets. It does work with dots.

**Comment by AaronDavidNewman** [comment]
Do we know how long this has been broken? 

There is an 'else' clause in the SVG arc method that is either incorrect, or being called incorrectly.  Another thing I noticed is that our debug bars are also missing the dot, because it comes to the same clause. `dot` works correctly because it is not drawn counterclockwise and doesn't fall into the same pit.

If I were going to fix this, I would consider using svg 'circle', which does exactly what we want.  I think this is coming about because we are trying to emulate canvas' arc command using a polyfill (canvas does not have 'circle').  We could create a 'circle' method in canvas context that makes the translation to 'arc'.  I don't really know anything about canvas, but I could probably figure out how to draw a circle if that's the way we want to go.

Interested to hear from @0xfe  and @tommadams who seems to be the last person to touch svg arc method.  I'm sure this has been discussed before.

SVG:
![image](https://user-images.githubusercontent.com/5438280/192107594-01c5e51f-393a-488b-a16e-e6a7abe73daf.png)

Canvas:
![image](https://user-images.githubusercontent.com/5438280/192107620-ad3cd3de-1deb-472a-abcd-0d35b5ce3f17.png)

``` typescript
arc(x, y, radius, startAngle, endAngle, counterclockwise) {
        // Handle the edge case where arc length is greater than or equal to
        // the circle's circumference:
        //   https://html.spec.whatwg.org/multipage/canvas.html#ellipse-method-steps
        if ((!counterclockwise && endAngle - startAngle >= TWO_PI) ||
            (counterclockwise && startAngle - endAngle >= TWO_PI)) {
... works correctly
        }
        else {
... 
            startAngle = normalizeAngle(startAngle);  // ADN: this sets start/end to 0 here if angle is 2*PI
            endAngle = normalizeAngle(endAngle);
  ... is broken
        }
```

**Comment by rvilarl** [comment]
Thanks a lot Aaron! Even if we decide to go for circles, it would make sense to fix the arc, would not it?

**Comment by rvilarl** [comment]
> Do we know how long this has been broken?

I introduced the prblem in tuplet 18 months ago. :worried: I do not know when the problem was included in rendercontext.

In any case a arc from 0 to 2PI counterclockwise is no arc. I will make a PR to fix it.

**Comment by AaronDavidNewman** [comment]
>> I introduced the prblem in tuplet 18 months ago.

Well...the interface for `svgcontext.arc` was an accident waiting to happen.  It's great that we are cleaning it up!
