### ISSUE TITLE
Refactor FontMetrics

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1485]
FontMetrics has two issues that I would like to resolve:
- the  different values are not consistenly located inside or outside the glyphs section.
- a lot of `any`

I will submit a PR including all the changes and smaller PRs (part of the previous one to facilitate the review)

**Comment by AaronDavidNewman** [comment]
a couple of pretty unrelated observations:

1. Shouldn't Font always have a `FontData` - no ?  (?)

2. Many classes, e.g. StaveSection have a `TEXT_FONT` that is never used and can be removed.

Just some random thoughts about the defaults:

The way I usually handle defaults in Smoosic, and I thing it might work well for font defaults:

``` typescript
export enum FontFamilyDefaults {
SANS_DEFAULT: 'Arial, , sans-serif ', SERIF_DEFAULT: 'Times New Roman, serif'
};

export interface FontInfo {
  family?: string;
  size?: number | string;
  weight?: string | number;
  style?: string;
  static get  defaults() {
  return {  family: FONT_FAMILY.SANS_DEFAULT, size: 10, weight: FONT_WEIGHT.NORMAL, style: FONT_STYLE.NORMAL };
  }
}
```
I think having a Font.SIZE is a little misleading since it's just a default for the size of a 'FontInfo'.  And music fonts have a different default size.  I realize this is a lot of trivial changes, but 90% of the time we want FontInfo.defaults whenever a text font is needed for a modifier.

I always find Font.ts confusing the way it mixes text and music fonts.  I don't know the solution because many nouns and verbs apply to both, so maybe what we have is the best it can be.  But maybe we should comment this - I find I need to relearn this every time I look at this code.

* FontInfo - only applies to text fonts
* FontModule - only applies to music fonts(?)
* FontData - applies to both music and text fonts
* FontMetrics - applies only to music fonts. 
* FontGlyph - applies to both music fonts and text fonts
* Font - a union of text and music font utilities, methods and data - a Font object could represent either a text font or a music font.

When we add 'FontKerning', that would apply only to text fonts.  If we decide to read music fonts directly from font files, I don't think any of this will change.

**Comment by rvilarl** [comment]
@AaronDavidNewman I have created a new issue with your comment. I agree that the mix today is not clear.
