### ISSUE TITLE
Question about new branches

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1517]
I notice some new branches appeared on the main repo, created by @mscuthbert 

<img width="1368" alt="S 2023-01-07 at 12 04 53 " src="https://user-images.githubusercontent.com/239113/211168561-99ec81a8-7ebd-406c-a61f-bda7bc4298e0.png">

Do you work directly with the `0xfe/vexflow` repo on your local machine? I know several of us have access to pushing to this repo, but generally I avoid checking out the 0xfe version and working on it as a my local working copy.

Instead, I forked 0xfe/vexflow to my account, and then I set this up

```
origin	git@github.com:ronyeh/vexflow.git (fetch)
origin	git@github.com:ronyeh/vexflow.git (push)
upstream	git@github.com:0xfe/vexflow.git (fetch)
upstream	git@github.com:0xfe/vexflow.git (push)
```

That way, all my new branches and pushes go to my own GitHub account.

When I'm ready, I submit a PR from my GitHub account to the 0xfe repo.

I think this avoids introducing extra branches into the 0xfe/vexflow repo, because I only push to `upstream` when I'm releasing.

**Comment by mscuthbert** [comment]
Ah -- I've generally been working directly off the 0xfe branch since that's what Github defaults to when you have write permission.  My thought is that branches don't take extra space, and I'm often interested in what other people are working on, especially when their work becomes stalled.  But if other maintainers don't want them there, I can switch to making my own fork, etc.  I just find that you get more stale masters for no extra gain.

**Comment by ronyeh** [comment]
I don't mind it at the moment. I was just surprised to find the new branches while browsing here, especially since we recently talked about deleting old stale branches.

Eventually if we move to a "organization repo".... it'd probably be good practice to each have our own forks of the main repo, even if we all technically have write access to pushing to the repo. It feels sloppy to me to have us all committing directly to this repo, even if it saves time & effort in the near term. :-)

**Comment by mscuthbert** [comment]
> I don't mind it at the moment. I was just surprised to find the new branches while browsing here, especially since we recently talked about deleting merged/stale branches.

I agree with deleting merged/stale branches -- if there's a merged branch, I think it can just be deleted without comment. (my tools do it 30 days after a merge if there are no further pushes), and if it's quite old--like over a year--, just dump it because it's probably not useful any more.  But a few weeks doesn't seem stale to me, especially for something difficult.  

If I'm the minority view on this then again, very willing to change.  I've found that teams of 2-20 work best on one repo w/o forks.  Beyond that, yes, forks are necessary.
