### ISSUE TITLE
OSMD issues/observations integrating 4.2.0-beta.0

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1520]
@sschmidTU has documented the folowing issues/observations
> New/Changed issues in Vexflow 4.2.0-beta.0 (PR [#1247](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1247)):
> 
> * [ ]  The last notes of a measure are now even further from the measure end, the margin is way too large in my view:
>   4.0.3:
>   ![image](https://user-images.githubusercontent.com/33069673/210880930-58099928-1d97-42ff-bd71-83d94800f8c3.png)
> 
> 4.2.0-beta.0: ![image](https://user-images.githubusercontent.com/33069673/210881010-30b3183e-99f5-4876-ae70-0d2e338b14b7.png)
> 
> diff: ![image](https://user-images.githubusercontent.com/33069673/210881080-902c674d-f4bd-4232-abc5-e246e0f855e7.png)
> 
> * [ ]  Scores are again much larger than in 4.0.3 (which was already larger than 1.2.93), probably because measures need more space. In our default piece (Beethoven Geliebte), 4 measures used to fit into row/system 2, now only 3 fit.
>   A good example of a much larger score is `JohannSebastianBach_PraeludiumInCDur` (3116 -> 4201 pixels high)
> 
> This is very obvious in `test_tuplet_consecutive_3and5_tuplets`. Is there maybe an issue with triplets using a lot of space? ![image](https://user-images.githubusercontent.com/33069673/210884389-be423f58-ddb9-4ab3-affd-3921128d246d.png)
> 
> ![image](https://user-images.githubusercontent.com/33069673/210884425-436c9c05-b2ec-4fbd-94af-4244ff851f4b.png)
> 
> or this one: ![image](https://user-images.githubusercontent.com/33069673/210884502-f84e6755-a948-4d48-9029-20992e2ba157.png)
> 
> Strangely, almost no size change in `test_tuplet_placement` ![image](https://user-images.githubusercontent.com/33069673/210884560-4332447d-82fc-43c5-817b-d53a8a087960.png)
> 
> There is definitely a certain mechanic at work here that changes the measure size a lot. Not sure how much on OSMD's or Vexflow's side.
> 
> * [ ]  tab sample `BrookeWestSample` errors and doesn't render:
> 
> ```
> Error: [RuntimeError] TickMismatch: Voices should have same total note duration in ticks.
> StackTrace: 
> Error: [RuntimeError] TickMismatch: Voices should have same total note duration in ticks.
>     at formatter.js:255:1
>     at Array.reduce (<anonymous>)
>     at Formatter.getResolutionMultiplier (formatter.js:253:1)
>     at createContexts (formatter.js:24:1)
>     at Formatter.createTickContexts (formatter.js:296:1)
>     at Formatter.preCalculateMinTotalWidth (formatter.js:213:1)
>     at VexFlowMusicSheetCalculator.calculateMeasureXLayout (VexFlowMusicSheetCalculator.ts:205:40)
> ```
> 
> Also a simpler tab sample: `OSMD_Function_Test_Tablature_Vibrato`, `_Alleffects`, `_Bends`, etc
> 
> I think we VexFlowPatched this to just ignore these mismatches, maybe specifically in tabs, it caused zero issues to just ignore the mismatch. I can look into this and why it doesn't work anymore with the current PR changes.
> 
> * [x]  Improvement: drum clef now aligned with other clefs
>   ![image](https://user-images.githubusercontent.com/33069673/210882521-f833a1a5-c924-453d-a516-1613a53e943c.png)
> 
> ![image](https://user-images.githubusercontent.com/33069673/210882566-0ee7d899-d957-4309-b6a2-3df32dcfb968.png)
> 
> ![image](https://user-images.githubusercontent.com/33069673/210882590-7e831e39-b2d9-426a-95a9-e95b639c079e.png)
> 
> * [x]  Improvement: grace note better positioned
>   ![image](https://user-images.githubusercontent.com/33069673/210882693-c8378c71-27ec-49fb-8035-ac01afdb6d70.png)
> * [x]  concern, but not critical yet: note distances sometimes very close, almost no padding
>   ![image](https://user-images.githubusercontent.com/33069673/210882908-d2412738-05c7-4759-a3cf-898c7da74223.png)
> 
> ![image](https://user-images.githubusercontent.com/33069673/210882959-520c0e7c-b8f1-440b-a252-817c25abffb6.png) (see Upmordent)
> 
> * [ ]  Voices not aligned anymore in `OSMD_Function_Test_Voice_Alignment`
>   ![image](https://user-images.githubusercontent.com/33069673/210883352-d0063ad3-2c2a-4e5c-8e30-069c5d1861e1.png)
> 
> ![image](https://user-images.githubusercontent.com/33069673/210883436-7a1cd3bb-8386-4743-8717-79a2799533c2.png)
> 
> ![image](https://user-images.githubusercontent.com/33069673/210883473-3da094c2-ff8f-4e42-b33e-6eef0936c0fc.png)
> 
> * [ ]  Rehearsal mark box around letter doesn't render in `test_rehearsal_marks_bolivia`. We had VexflowPatched this. Maybe I can look into this.
>   ![image](https://user-images.githubusercontent.com/33069673/210883861-4a825591-23bf-4c95-832f-f506126507cc.png)
> 
> ![image](https://user-images.githubusercontent.com/33069673/210883884-81ae948d-5f62-458a-a0fa-bb497c5eedf4.png)
> 
> ![image](https://user-images.githubusercontent.com/33069673/210883899-d6403035-b8a6-4e3b-9f45-f3ef207f236f.png)
> 
> more simply in `test_rehearsal_marks_simple_one_measure`: ![image](https://user-images.githubusercontent.com/33069673/210883979-b5266b60-f70d-4a5a-a8eb-4251dc4f985a.png)
> 
> ![image](https://user-images.githubusercontent.com/33069673/210884027-02d61c5c-a4a7-4f8b-bcd6-a770244e18df.png)
> 
> * [x]  Improvement: `test_string_number_collisions`
>   ![image](https://user-images.githubusercontent.com/33069673/210884167-29541e5c-e202-4572-98d1-96c7650f7d09.png)
> 
> ![image](https://user-images.githubusercontent.com/33069673/210884192-2c30693f-e3d9-4d49-9851-ebfb477bf11f.png)
> 
> * [ ]  Consecutive Tuplet number hiding doesn't work anymore:
>   ![image](https://user-images.githubusercontent.com/33069673/210884746-d0e373a3-3a23-4f78-82ec-5e552f7ec433.png)
> 
> ![image](https://user-images.githubusercontent.com/33069673/210884792-0857ab51-1c66-4cf6-a7a3-d9e6ff7a82b7.png)
> 
> see the variables `TupletNumberLimitConsecutiveRepetitions`, `TupletNumberMaxConsecutiveRepetitions`, etc. in EngravingRules.
> 
> I can probably look into this.
> 
> * [ ]  Pedal brackets rendering causes errors, so we have to disable this in this PR via `osmd.EngravingRules.RenderPedals = false` to for example be able to render our default piece, Beethoven Geliebte. I can look into this, we have a VexFlowPatch for pedalmarking which adds a function setEndStave(). Would be nice to get this into vexflow via a PR, I'll see if I can do that.
> 
> ```
> Error loading sheet: TypeError: pedalMarking.setEndStave is not a function
> StackTrace: 
> TypeError: pedalMarking.setEndStave is not a function
>     at VexFlowPedal.getPedalMarking (VexFlowPedal.ts:126:35)
> ```
> 
> This is a quick look, I think we can take it from here and work on these first. It's quite a bit to fix, but we can take it one at a time, step by step!
> 
> I'll still merge this so that we have a clean slate to work from (and clean diffs moving forward).

**Comment by AaronDavidNewman** [comment]
> The last notes of a measure are now even further from the measure end

Good eye.

The right margin can fall anywhere between:
```
   endPaddingMax: 10,
    endPaddingMin: 5,
```
But here, we end up with > 10px from the right of the lyric to the barline.

Maybe the problem is with the formatter.  When there is over/under flow, the formatter addresses this by changing the width over which we format, so the proportionality stays the same but basically the scale of the distance between notes expands/contracts.  But we don't rescale the padding, so if we underflow and increase the 'width' of the measure, we should proportionally increase the max (and min) padding.

The problem in the other direction usually isn't so noticeable, because the relative padding is scaled down but the padding will always be >0.

So, logically it looks like this.  The scale changes but the padding is the same if there is underflow, so the padding is less relative to the new scale.  We should also increase the min/max padding when we increase the scale, and visa-versa.

```
iteration 1:
|    x   x   x      |
iteration 2:
|    x    x    x  |
```

This will require some experimentation.  If we just change the padding at the same rate as the width, it seems like the error will never change, but I am not positive about that.  Changing the justify width doesn't change the width of the notes, so the note width will seem relatively larger at a smaller scale.

In a weird way this reminds me of [special relativity](https://en.wikipedia.org/wiki/Lorentz_transformation)

![image](https://user-images.githubusercontent.com/5438280/211203468-fbf0823a-16a7-484b-87e4-0637206f9098.png)

**Comment by AaronDavidNewman** [comment]
After all that wind, I'm thinking there may not be a bug here :)

The issue for me was the width I was justifying the voices over.  Is it possible OSMD has the same issue?  In the case of smoosic, I was overestimating the width of the staff modifiers at the start of the system.  I added some debug code to record the formatting width.

The dark blue box shows the formatting width.  Start x is always the same based on the staff modifiers, so if the format width is smaller than the available width, the music will be skewed to the left.

![image](https://user-images.githubusercontent.com/5438280/211246794-3106aac3-5911-4b6e-8e6c-faeaef4e72c4.png)

Here is the version with the calculation for the starting symbols corrected.

![image](https://user-images.githubusercontent.com/5438280/211247398-6920e017-1478-43e9-9037-39179a18054a.png)

barline is in the same place, but the music is formatted better because the justified width and the available width in the staff is the same.

**Comment by sschmidTU** [comment]
@AaronDavidNewman Interesting, thank you so much for providing this much information!
So, which Vexflow calls or which part of our layout calculation do we need to adjust? Is it about the padding at the start of the measure?
I think the main width result comes from `formatter.preCalculateMinTotalWidth(allVoices)`, so I'm not sure where the padding comes in there or why it changed between Vexflow 4.0.3 and 4.2.0-beta. Basically, we didn't change anything except updating to 4.2.0-beta, and the padding to the end of the measure increased a lot in many cases.

**Comment by ronyeh** [comment]
I just released `4.2.0-beta.2` with the most recent changes to softmax, etc.

`npm install vexflow@beta`

**Comment by AaronDavidNewman** [comment]
There were some changes to annotation formatting - before, annotation formatter was claiming too much width.  So that might be the difference in your measures with lyrics.

So if it looks like this, 'B' is `stave.getNoteStartX()`.  The justify width you send to formatter should be C - B.  The width of the staff is C - A.  If C - B when rendered is more than the justify width you provide, you will have this problem.   The challenge is that you don't always know where 'B' will be.

```
A        B        C  
| c t ks <music>  |
```

This is the code in smoosic, not sure if you are doing this or using formatToStave or something else. 

``` typescript
    this.stave = new VF.Stave(staffX, staffY, fullStaffWidth);
    this.formatter = new VF.Formatter({ softmaxFactor: this.softmax, globalSoftmax: false });
    this.voices.forEach((voice) => {
      this.formatter.joinVoices([voice]);
    });
// ...  possibly add more voices to 'voices' and create more staves
formatter.format(voices, justifyWidth);
```

**Comment by mscuthbert** [comment]
I have found that the softmax setting is not being applied to the last note of a Stave.  Was trying to work through this and diagnose on my own system, but thought that I would share.  Whatever % of the measure's ticks the last note occupies, it is being rendered at the same position in the stave

**Comment by AaronDavidNewman** [comment]
> Whatever % of the measure's ticks the last note occupies, it is being rendered at the same position in the stave

Can you show a picture of what you mean?  It does, that's line 870 in formatter.  softmax is from note to the previous note, and the last note isn't anyone's 'previous' note.  But it recalculates the padding of the last note, based on the softmax %.  I think.

![image](https://user-images.githubusercontent.com/5438280/211691799-6b9c1373-9681-44dd-860f-74e365a9df15.png)

![image](https://user-images.githubusercontent.com/5438280/211692104-2d307641-05be-4e52-ae59-89afbfa11b23.png)

**Comment by ronyeh** [comment]
@rvilarl what other issues do you plan to work on for this release? Are we close enough to issue another beta and then start comparing the scores for visual differences, etc?

**Comment by rvilarl** [comment]
@ronyeh nyeh I am planning to:
1) finish with the removal of points in the common file
2) move Gonville to the common file 

Then with the new beta reasses the OSMD issues. We can make intermediate releases, I agree with you: we should compare our rendering with other tools.
