### ISSUE TITLE
prevent chord symbols from affecting the layout of notes

### ISSUE THREAD

**Issue by EugenDueck** [0xfe/vexflow#1524]
When adding chord symbols, the notes move to the right, although I don't see a need for that. It leads to odd spacing. The following screenshots were created from identical code, except for the addition of a chord symbol to the first note. The wider the chord symbol, the more the notes move to the right.

To wit: https://jsfiddle.net/m27xLo1a/

![Screenshot from 2023-01-13 17-51-19](https://user-images.githubusercontent.com/41422/212279195-b2cbed3c-e963-4fbe-8d8a-eb079b544e35.png)
![Screenshot from 2023-01-13 17-52-58](https://user-images.githubusercontent.com/41422/212279296-3def8178-a274-4549-bc3f-dde35e87d8a0.png)
![Screenshot from 2023-01-13 17-53-26](https://user-images.githubusercontent.com/41422/212279315-85fd706c-20e1-456a-91e9-933753b36d91.png)
![Screenshot from 2023-01-13 17-57-46](https://user-images.githubusercontent.com/41422/212279563-5c862a94-6897-43e7-aa57-9e85cd511fac.png)
![Screenshot from 2023-01-13 17-53-30](https://user-images.githubusercontent.com/41422/212279245-b8fa4e73-b116-406e-8881-6ee98002f5e5.png)

How can I avoid this from happening?

**Comment by mscuthbert** [comment]
The layout of notes should be affected by chord symbols, but not the initial position.  If anything the next note needs to move to the right and a chord symbol on the first note should not affect first note placement unless the symbol is centered above it, which here it clearly isn't.

I think we're looking at one introduced layout bug that is affecting a lot of things.

**Comment by EugenDueck** [comment]
I just ran that test with 4.0.3, and the result is identical to 4.1.0, i.e. the displacement of the first note got worse with 4.0.3.

**Comment by rvilarl** [comment]
@AaronDavidNewman could you look into that? I believe that you made some adjustments to chords already

**Comment by AaronDavidNewman** [comment]
There is a `setReportWidth` in chord symbols that should do what you want if you set it to false.  This is because often in jazz, you have a chord change over many notes and you don't want the chord change to affect the a layout of the notes.

The way modifiers work in vexflow is that there is a left and right extent for each modifier - whether chord change, accidental, tab slide or whatever.  The left extent will offset the notehead, even for the first note. So for example, if the notehead is 12 and the chord is 14 and centered, it will add one to the left and one pixel to the right.

Ideally, we would track bounding boxes for all the modifiers, and only change the width if it was required.  But that is a hard problem and would require a pretty major rewrite of the pre-format logic.  

Here's an example of 'setReportWidth' set to false.  In Smoosic this is the default for chord changes, and optional for annotations/lyrics.

![image](https://user-images.githubusercontent.com/5438280/212369397-4229c7fb-c43d-4a78-8a80-f8de2123156f.png)

**Comment by EugenDueck** [comment]
Thanks Aaron. `setReportWidth(false)` does the trick. https://jsfiddle.net/euomkjg7/
![image](https://user-images.githubusercontent.com/41422/212436608-c3370f9e-b88f-4117-a3d4-1fbd2a3baa56.png)
