### ISSUE TITLE
npm packages upgrade

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1551]
I have used npm-upgrade to resolve the vulnerabilities reported by dependabot. They are all now resolved.
@ronyeh I had to remove the `eslint` section of `fork-ts-checker-webpack-plugin` this is no longer supported.

I found the following issue:
- we use the qunit version stored in tests/support regardless of the install qunit package.
- as a consequence of the above `grunt-contrib-qunit` must stay in version 5. Update to 6 or 7 is not possible.

by the way there is a @types/qunit package with the typescript definitions of qunit.

**Comment by ronyeh** [comment]
Yes, even when I upgraded all the tests, I never upgraded qunit because it was a major version upgrade and much more verbose than the old QUnit we were using.

It is certainly possible, but it would be a rather big PR to upgrade to the most recent QUnit. Maybe we leave that project for the VexFlow 5.0 release?

**Comment by rvilarl** [comment]
I agree let us leave it for 5.0

I also believe that we have to rework the tests in order to use factory see #775 In the end of the day these tests are the examples that the users search to know how to do things with the lib.

**Comment by rvilarl** [comment]
Addressed in #1562
