### ISSUE TITLE
Error: Dot.buildAndAttach is not a function

### ISSUE THREAD

**Issue by the-drunk-coder** [0xfe/vexflow#1630]
Hi,

I'm trying to draw dotted notes, but somehow I'm getting an error that 

```
Uncaught TypeError: Dot.buildAndAttach is not a function
```

Not sure how to fix this ... I'm on latest Vexflow 4, using the `vexfow4` package from npm ...

**Comment by AaronDavidNewman** [comment]
You really need to share some code with us on a fiddle or something.  buildAndAttach is a static method of Dot, so make sure you import {Dot}.

**Comment by the-drunk-coder** [comment]
Here's the relevant code as copied from my project, with the difference that I import from `node_modules` instead of from the web: 

https://jsfiddle.net/adzty1kf/

In my project I import via:
```
<script src="/node_modules/vexflow4/releases/vexflow-min.js"></script>
```
instead of:
```
<script src="https://cdn.jsdelivr.net/npm/vexflow@4.2.5/build/cjs/vexflow.js"></script>
```

The fiddle works, though, and in fact, when I use the second variant in my project, it works as well ... so maybe there's something broken in the npm release ?

**Comment by AaronDavidNewman** [comment]
When I look in 'vexflow-min.js', I see this at the end:

```
// YOU ARE LOOKING AT VEXFLOW LEGACY VERSION 3.0.9.
// SEE THE `build/` FOLDER FOR THE NEWEST RELEASE.
```

So that is likely your issue.  Use the build/cjs version of vexflow.js or vexflow-debug.js

**Comment by the-drunk-coder** [comment]
hmm that's odd, as I'm using a package from npm that has only been created about a month ago, as indicated in this comment:

https://github.com/0xfe/vexflow/issues/1625#issuecomment-2212523601

It's marked in npm as version 4.2.5 --> https://www.npmjs.com/package/vexflow4

In my `package.json` I use that version number as well: 
```
"dependencies": {
        "osc": "2.4.0",
        "vexflow4": "4.2.5"
    }
```
So if `vexflow-min.js` really is version 3.0.9, then that'd be really counterintuitive ...

**Comment by AaronDavidNewman** [comment]
The code and versions in build directory are 4.2.5.  The releases directory is pre-built.  I think they keep some older version around for the visual regression tests, or maybe it was an oversight (maybe @ronyeh has an idea).  

I think in all cases you want to use one of the packages in /build/cjs, as this would have been build with latest source code.

**Comment by ronyeh** [comment]
Hello @AaronDavidNewman and @the-drunk-coder,

Sorry for the confusion! Yes, we had been keeping around the legacy version of VexFlow (v 3.0.9) in the releases/ directory.

This was because some old websites and old JSFiddles that depended on v3.0.9 linked directly to:
`https://unpkg.com/vexflow/releases/vexflow-min.js`

If we had removed the releases/ directly when we published v4.x, we would have broken those old sites. Even if we put v4.x into the releases/ directory, we would have broken those old sites, since 4.x introduced breaking changes.

Yes, it's confusing that we ship the legacy version alongside the current one in the build/ directory.

4.x has been out long enough now (and we're working on 5.x). I think it's time we remove that releases/ folder. It's OK if those older JSFiddles break. :-)

I'll introduce a PR to remove the releases/ folder from the NPM package.
