### ISSUE TITLE
Support for double whole note

### ISSUE THREAD

**Issue by samaxes** [0xfe/vexflow#297]
Is it possible to add support on VexFlow for double whole note?

**Comment by gristow** [comment]
Double whole notes (aka breves) are already fully supported -- their duration value is "1/2" (must be expressed as a string).  For instance:
```
var note =   new Vex.Flow.StaveNote({
    keys: ["Bb/4"],
    duration: "1/2"
});
```

**Comment by samaxes** [comment]
I'm using [ring's fork](https://github.com/ringw/vexflow/tree/musicxml) to support MusicXML files generated by Finale and I'm getting the following error when calling `Vex.Flow.parseNoteData(note_struct)`:

```
Invalid note initialization object: {"clef":"treble","keys":["C/4"]}
```

I believe this issue is VexFlow related since ringw's fork only converts the XML file content into VexFlow format. If not, please let me know.
The MusicXML file I used can be found here: http://pastebin.com/Ze6i9AmW.

**Comment by gristow** [comment]
Ok -- the issue is in ring's fork.  Although VexFlow supports double whole notes (as does MusicXML), when the fork is initializing a `Note` that should be a double whole, it's either not providing the required "duration" value in the `Note` initialization object or providing an incorrect one, which is causing VexFlow to throw that error.

I don't know the fork -- but would suggest you close the issue here, and open one there!

**Comment by gristow** [comment]
Yes -- just glanced at ringw's fork -- the issue is in `musicxml.js`.  Change lines 301 and forward to read:
```
        noteObj.duration = {
          breve: "1/2", whole: "1", half: "2", quarter: "4", eighth: "8", "16th": "16",
          "32nd": "32", "64th": "64", "128th": "128", "256th": "256"
        }[type];
```

And it should work just fine.

**Comment by samaxes** [comment]
Thanks @gristow for the help!
With that change in place, the code doesn't crash anymore.
However, the note is rendered as a half note instead of a breve (the code only takes into consideration what's after the `/` char).

**Comment by gristow** [comment]
Ok -- sorry that didn't fix it. Unfortunately, I don't have time to go digging into the MusicXML in @ringw's fork to find where the problem is. You might reach out to him. The support for breves is fine in VexFlow itself.  Try the following code in the [VexFlow sandbox](http://www.vexflow.com/docs/sandbox.html), for example:

```
// Get the rendering context
var canvas = $("div.sandbox div.sandbox canvas")[0];

var renderer = new Vex.Flow.Renderer(canvas,
Vex.Flow.Renderer.Backends.CANVAS);
var ctx = renderer.getContext();
renderer.resize(500, 300); // Resize and clear canvas
ctx.setFont("Arial", 10, "").setBackgroundFillStyle("#eed");

// Create and draw the tablature stave
var stave = new Vex.Flow.Stave(10, 10, 500);

note = new Vex.Flow.StaveNote(
      { keys: ["c/4"], duration: "1/2"});

var voice = new Vex.Flow.Voice(Vex.Flow.TIME4_4).setStrict(false);
voice.addTickables([note]);
  var formatter = new 

Vex.Flow.Formatter().joinVoices([voice]).formatToStave([voice], stave);

note.setStave(stave);
voice.draw(ctx, stave);
stave.setContext(ctx);
stave.draw();
```
Which results in:
![image](https://cloud.githubusercontent.com/assets/8905340/8553927/bd546456-24b4-11e5-9385-d20883518a1b.png)

**Comment by ringw** [comment]
Thanks for pointing this out! I'll look into this issue some time soon. In the meantime, feel free to close this issue and open a new one on my fork, at least to remind me to take a look at it.

**Comment by samaxes** [comment]
Thanks again for the help @gristow!
@ringw, can you please enable the issues option on your project settings?
I will open a new issue there.

**Comment by ringw** [comment]
Done!

**Comment by samaxes** [comment]
Thanks @ringw.
I'm now closing this issue.
