### ISSUE TITLE
Changing the end clef modifies the initial key signature

### ISSUE THREAD

**Issue by iolucas** [0xfe/vexflow#331]
The **end clef** in a stave must modify **only** the Y offset of the **end key signature**, but it is modifiying the **initial key signature** aswell.

![image](https://cloud.githubusercontent.com/assets/10436644/14022370/44ecceae-f1be-11e5-9949-e1d6e6da5883.png)

A possible fast solution would be add a new parameter to the methods which add keys to optionally choose the clef for it.

**Comment by mscuthbert** [comment]
Award for most visually clear bug report ever?
Unrelated, but noticeable in the same image: in this case, the repeat sign needs to go before the bass clef sign, because it only affects the music after the repeat.  But there are cases where the repeat needs to go after the clef (or even after the key signature change) such as when the clef at the end of a repeat passage is different from before it -- so there needs to be some way to make this ordering mallable.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by lucasolivier** [comment]
> Award for most visually clear bug report ever?

Thanks :)

> Unrelated, but noticeable in the same image: in this case, the repeat sign needs to go before the bass clef sign, because it only affects the music after the repeat. But there are cases where the repeat needs to go after the clef (or even after the key signature change) such as when the clef at the end of a repeat passage is different from before it -- so there needs to be some way to make this ordering mallable.

I think the best approach to solve this kind of issue would be a stack design of the stave elements, such those implemented with clefNote, barNote etc. Also decouple all the possible staff music rules from the lib and let the user deal with them, since there is a great number of variations available.

**Comment by sug1no** [comment]
<http://jsfiddle.net/yjn53z9p/>

![image](https://user-images.githubusercontent.com/3293067/49404597-41bda180-f793-11e8-83ae-45f5a2d72e8a.png)
