### ISSUE TITLE
Version 1.2.50 broke IE support

### ISSUE THREAD

**Issue by mutil** [0xfe/vexflow#404]
From v1.2.50 upwards, Internet Explorer (9 & 10 -- 11 not tested, Edge seems unaffected) throws error: `RuntimeError: The provided duration is not valid: undefined`. 
I don't know if this was intentional or you don't mind for IE support anymore, but maybe there should be a browser/version compatibility matrix somewhere in the documentation.
Thank you.

**Comment by Silverwolf90** [comment]
This was unintentional as the tests pass in IE. Can you provide more information about your error?

**Comment by mutil** [comment]
Well, I don't know how I can be of more help. You can reproduce this with an `index.html` containing step 1 and the first half of step 2 of the tutorial. Throws the error provided above with vexflow version > 1.2.49 in IE10 and IE9. (I don't have IE11 at the moment).

**Comment by Silverwolf90** [comment]
[I suspect the reason is that class inheritance in Babel does not support IE9/10. The `super` keyword doesn't resolve appropriately.](https://babeljs.io/docs/usage/caveats/)

@0xfe We can probably fix this by using the [`es2015-loose`](https://github.com/bkonkle/babel-preset-es2015-loose) babel preset

**Comment by 0xfe** [comment]
I think the best thing to do here is:

1) Mark `1.2.50` as bad and release `1.2.51` using `es2015-loose`.
2) Officially kill support for IE9/10 and bump the major version.
3) Provide a mechanism for users to build unofficial IE9/10 versions (e.g., this could be as simple as adding a wiki page with instructions on enabling `es2015-loose`.)

Thoughts?

**Comment by mscuthbert** [comment]
I like this, but how hard would it be so that after the major version bump to have the release mechanism build the unofficial/untested IE9/10 version for at least a year or two as a separate file in .src that people could include instead of the main .js file if they need it? (sort of like how the build system creates a -debug and a -min version).  If the answer is easy then it might be worth considering keeping it on.  Thanks!

**Comment by Silverwolf90** [comment]
That all sounds fine to me. Adding a grunt task to compile with `es2015-loose` would be pretty trivial.
