### ISSUE TITLE
Regression: Breve noteheads have incorrect width

### ISSUE THREAD

**Issue by 0xfe** [0xfe/vexflow#430]
Looks like the glyph bounding boxes don't account for the little double-bars beside the note heads?

<img width="635" alt="screen shot 2016-08-24 at 3 03 48 pm" src="https://cloud.githubusercontent.com/assets/241299/17944070/1bac52fa-6a0c-11e6-99ac-f781f0186d7b.png">

**Comment by Silverwolf90** [comment]
The bounding box width is accurate according to the bounding box tests.

![image](https://cloud.githubusercontent.com/assets/1631625/17981632/586f9f30-6afc-11e6-9722-b0087c773fd4.png)

I'm not sure this is a bug. The test places the chords using an fixed offset, so they were probably pretty close to colliding before, and the combination of using real notehead widths and increasing default glyph size resulted in this collision.

But it's I'd still bet that the displacement amount should be different. Are the middle bars supposed to overlap? Or are they supposed to be omitted entirely so that you only have bars on the left and right of the chord? Behind Bars doesn't talk about this case and I can't recall seeing this case in any of the music notation I've come across.

**Comment by 0xfe** [comment]
Yeah, the bounding boxes look right. Let me take another look at the tests and see what's up.
