### ISSUE TITLE
fillStyle on noteheads doesn't always work -- styles not persistent

### ISSUE THREAD

**Issue by andiejs** [0xfe/vexflow#473]
The code below adds a fillStyle to two of the noteheads; it is only visible on one. seems to not work on noteheads that are beamed.

I can confirm that the style is initially being set on the notehead, but I suspect the notehead is regenerated at some point between the style being set, and actual drawing. the style is not saved or maintained anywhere (e.g. in the stavenote) , so it disappears and is ultimately "undefined".

---------------------------
```javascript
VF = Vex.Flow;

// Create an SVG renderer and attach it to the DIV element named "boo".
var div = document.getElementById("boo")
var renderer = new VF.Renderer(div, VF.Renderer.Backends.SVG);

// Configure the rendering context.
renderer.resize(500, 500);
var context = renderer.getContext();
context.setFont("Arial", 10, "").setBackgroundFillStyle("#eed");

// Create a stave of width 400 at position 10, 40 on the canvas.
var stave = new VF.Stave(10, 40, 400);

// Add a clef and time signature.
stave.addClef("treble").addTimeSignature("4/4");

var notes = [
new VF.StaveNote({ keys: ["a/4"], duration: "4d" }).addDotToAll().setKeyStyle(0,{fillStyle:"#AAA"}),
new VF.StaveNote({ keys: ["b/4"], duration: "8" }).
addAccidental(0, new VF.Accidental("b")),
new VF.StaveNote({ keys: ["c/4"], duration: "8" }),
new VF.StaveNote({ keys: ["d/4"], duration: "8" }),
new VF.StaveNote({ keys: ["e/4"], duration: "8" }).
addAccidental(0, new VF.Accidental("b")),
new VF.StaveNote({ keys: ["d/4"], duration: "8" }).
setKeyStyle(0,{fillStyle:"#AAA"})
];


var beams = VF.Beam.generateBeams(notes, {groups : [ new Vex.Flow.Fraction(1,4) ]});
Vex.Flow.Formatter.FormatAndDraw(context, stave, notes);
beams.forEach(function(b) {b.setContext(context).draw()})
// Connect it to the rendering context and draw!
stave.setContext(context).draw();
```

**Comment by Silverwolf90** [comment]
Yeah this looks like a bug to me! If you call `setKeyStyle` after `generateBeams` it seems to work.

https://jsfiddle.net/7290eukt/

**Comment by gristow** [comment]
Mainly leaving this comment as a debug note to myself:
- beam.js calls `staveNote.setStemDirection()`, inherited from `StemmableNote`
- `setStemDirection` calls `this.reset` in this case on the `StaveNote` prototype
- `this.reset` calls `this.buildNoteHeads()` which creates new note heads, losing any previous styles applied.

Possible Solutions:
- `StaveNote.setKeyStyle()` could keep an array of `NoteHead` styles on `StaveNote` to be applied at time of drawing, instead of applying directly to `StaveNote` 
- `StaveNote.reset()` could check for any previous `NoteHead` styles on existing `NoteHead`s before destroying. (This doesn't seem very clean, given the naming of 'reset'...)
