### ISSUE TITLE
Fixed bar width support ?

### ISSUE THREAD

**Issue by gaspard** [0xfe/vexflow#494]
Is there a way to tell the formatter to use a fixed amount of width for each bar ?

This improves rhythm pattern readability.

**Comment by Silverwolf90** [comment]
Hi @gaspard,

I'm not completely sure I understand, are you talking about providing a default width if no width is provided? Showing me some code to put your question in context might help.

**Comment by gaspard** [comment]
I am working on a tool to create scores for beginners and it helps if the width of every bar in the score is the same (linear mapping of musical time to horizontal distance on stave).

All the code is here:

https://github.com/lucidogen/cvs-solfi/blob/master/src/lib/vexdraw.ts#L75

**Comment by Silverwolf90** [comment]
Ah I see. The issue right now is that you are treating the `Stave` as the stave for the *full line* of music. The more idiomatic way is to think of the `Stave` more as a "staff slice" where you create a `Stave` for each measure. Then you have full control over the width. And for formatting, instead of using `Formatter.format(voices, width, options)` you would use `Formatter.formatToStave(voices, stave, options)`

**Comment by gaspard** [comment]
Thanks, will try this :-)
