### ISSUE TITLE
How can I transpose (change key)?

### ISSUE THREAD

**Issue by benlieb** [0xfe/vexflow#542]
I am trying to make an app that will read and display musicxml files in a browser and be able to render the musicxml doc in different keys.

In my research for tools that I might use I have found that the VexFlow MusicXML plugin (https://github.com/mechanicalscribe/vexflow-musicxml) can do most of what I want (it can load musicxml files and render them).

Unfortunately it does not seem to be able to transpose them. Is there a native way in VexFlow to render the musicxml document in another key?

Thanks!

**Comment by gristow** [comment]
VexFlow is really just designed to handle the rendering of music -- there's very little support for musical-theoretical concepts. If you wanted to implement something like this yourself, you could catch the `parseNote()` call in [Mechanicalscribe's vexflow-musicxml repository](https://github.com/mechanicalscribe/vexflow-musicxml).

Around line 300 in musicxml.js you'd insert your transposition logic -- perhaps using a music theory library such as [Teoria](https://github.com/saebekassebil/teoria) to do the heavy lifting.

A word of caution: It's not always so easy as saying "transpose everything up a whole step" -- you'd need to watch out for impossible accidentals (like triple sharps/flats) and sometimes change to enharmonic keys (using Ab major instead of G# major when transposing up a Major 3rd from E Major, for instance).

In any case, hope this helps point you in the right direction!
