### ISSUE TITLE
A way to delete stave/canvas

### ISSUE THREAD

**Issue by ManuelVargas1251** [0xfe/vexflow#546]
Wondering if there's a way to delete the completed stave to make room for a new one.

**Comment by SalahAdDin** [comment]
Good question.

**Comment by gristow** [comment]
Two options: paint a rectangle over it the same color as the background
``` JavaScript
  context.rect(x, y, width, height, { stroke: 'none', fill: 'white' });
```

Or, if you're using the SVGContext, open a group before you start drawing anything in the measure. When you want to delete & repaint the measure, remove that group. This is cleaner -- in case any elements from another staff (a slur, etc...) overlap the measure you're deleting.
``` JavaScript
  // Open a group to hold all the SVG elements in the measure:
  const group = context.openGroup();

  // Draw your measure as you normally would:
  voices.forEach(voice.draw(context, stave));

  // Then close the group:
  context.closeGroup();

  // And when you want to delete it, do this:
  context.svg.removeChild(group);
```

**Comment by thipages** [comment]
Hi,
I reopen here since I find difficult to manage erasing a stave. What I try to achieve : to create a stave on the fly according to notes entered in a textInput (or TextAera) for stave pattern registration. When the user enters the notes, it updates (when valid) the corresponding stave.

So I need to be able either

- to add/change notes on the fly
- or to erase the stave and replace by a new one after keyUp event.

I created a [simplified FIDDLE](https://jsfiddle.net/thipages/cpp6c5op/3/) using setInterval to simulate the keyUp. You will see that it works if I erase the div score container. However, this seems to be a bit heavy way to do it (instanciation of all API at every loop)

Any ideas for being more efficient?

Thank you for your support

**Comment by gristow** [comment]
Support for this sort of thing in using `EasyScore` is quite limited, so the way you are doing it is in fact the correct way even though it's a bit heavy.

If you switch to using the full VexFlow api, you'll have the option of just redrawing certain parts of your rendered score, which can be more lightweight. (And, with `SVGContext` you'll also be able to remove elements from the rendered SVG without having to redraw everything, re-create objects.)

**Comment by thipages** [comment]
ok. When I will need it, I will share such an implementation. Thank you.

**Comment by SalahAdDin** [comment]
Thank you for share with us your implementation.

**Comment by ManuelVargas1251** [comment]
I ended up using jquery to remove the staff with its ID and redrawing it. 

```javascript
$("#staff_id").empty();

**Comment by gristow** [comment]
Alternately, if you don't want to pull in jquery, plain vanilla javascript will do:

``` javascript
const staff = document.getElementById('staff_id');
while (staff.hasChildNodes()) {
    staff.removeChild(node.lastChild);
}
```

**Comment by stevage** [comment]
Shorter:

```
document.querySelector('#staff_id').replaceChildren()
```
