### ISSUE TITLE
Tuplets -- single-note tuplet // for notating unusual rational rhythms

### ISSUE THREAD

**Issue by andiejs** [0xfe/vexflow#548]
I'm setting up to use the powerful tuplet support supplied by @gristow to try to notate some unusual rhythms. 

I'm wondering why an error is thrown if the list of notes to be tupletized has length 1. The error is thrown from a check early in the tuplet process, before it's clear that it's really going to cause any problems.

I think it makes sense to have tuplets of length 1, e.g. if I have a single note of duration 1/7 and I want to notate it as an eighth-note, then I need to multiply it by 8/7.

Here's my general idea about how to notate the kinds of rhythms I'm working with.
Example measure durations: (1/7, 1/7, 2/9)
The sum of this is 32/63, so we can make an approximate measure of 2/4 time and tuple the whole measure by 64/63 to make it fit. This gives:

   
|------64/63-----------|
9/64 9/64 7/32

This is notatable, but in the general case it may not be, and anyway it would be better if the notes looked simple. So we can add a second (inner) layer of tuplets for each note/group of notes, to approximate them to (e.g.) eighths. 

    
|---------64/43-------|
|----9/8------||--7/8----|
  1/8 1/8 -------    1/4
 
Now everything adds up and is notated in "square" measures and notes.

---
One further thing would be to be able to change the way the tuplets print their numeric labels. The above is not clearly legible as (1/7, 1/7, 2/9). This means decoupling the label from the actual multiplier and allowing the user to specify it directly, overriding the default. E.g. we could relabel to show the true duration of an eighth-note.

    
|---1/7-------||----1/9--|
  1/8     1/8 -------  1/4

**Comment by SalahAdDin** [comment]
@0xfe,hrlp please

**Comment by gristow** [comment]
I did some quick testing on this and it looks like you're right that there's no reason to not permit single-note tuplets. Here's a [fiddle](https://jsfiddle.net/gristow/q04ysmqf/) showing the basic concept, which would look like this:
![screen shot 2017-06-18 at 9 45 39 am](https://user-images.githubusercontent.com/8905340/27261155-ede4cb88-540a-11e7-984c-10e0702dce7a.png)

This is a quick change, I'll try and get it pushed in the next couple of days.

**Comment by gristow** [comment]
@dinukadesilva since you mentioned you'd like to contribute -- this issue is a pretty easy fix and would be a good way to get familiar with the build/testing process for the repository. Want to tackle it?

The todo for this:
- Remove lines 71-73 from tuplet.js
``` javascript
    if (notes.length === 1) {
      throw new Vex.RuntimeError('BadArguments', 'Too few notes for tuplet.');
    }
```
- Run the tests and be sure nothing is broken (`grunt test`)
- Run the [visual regression tests](https://github.com/0xfe/vexflow/wiki/Visual-Regression-Tests) and be sure nothing changed
- Add a test with a singleton accidental or two (you might use this [fiddle](https://jsfiddle.net/gristow/q04ysmqf/) as an example) to tuplet-tests.js
- Add the new image file that's created from visual regressions to the build/images/blessed folder & commit it.
- Test everything again
- Send in a PR
