### ISSUE TITLE
Trying to work in SVG mode not working

### ISSUE THREAD

**Issue by crashcourse64** [0xfe/vexflow#554]
I am following these https://github.com/0xfe/vexflow/wiki/Animation-with-VexFlow-&-CSS instructions. I have copied the configuration verbatum, but error occurs: SVGConext is not defined. I have vexflow-debug.js included as a script. I'm not entirely sure if it defines SVGConent but it seems to. Anyway, I include svgcontent.js which seems sensible but it returns werror: Unspected token input.

Can you help?

**Comment by gristow** [comment]
Without seeing the exact code you're using it's very hard to answer this. (Also: watch out, you have three typos in your question 'SVGConext' and 'SVGConent' both of which should be 'SVGContext' I imagine. There is no 'svgcontent.js' only 'svgcontext.js', and you should never need to include it if you have vexflow-debug.js loaded.)

I would suggest starting by copying all of the code directly from [the jsfiddle on that page](https://jsfiddle.net/gristow/Ln76ysjv/) since it executes sets up the boilerplate rendering code, which is where it sounds like you might be having issues.

**Comment by crashcourse64** [comment]
Thanks for your reply. Sorry about typeos. There is a jsfiddle linked to the tutorial. However, it has different commands. The jsfiddle doesn't get SVGContext (right?) at all - it is quite different in that reguard. It does use the resource vexflow-debug.js and works fine but doesnt using SVGContext. 

I am that uncomforatble stage of learning a new API right at the beginning and everything is somewhat mysterious. Thaks for any other help.

Ian

**Comment by gristow** [comment]
So: vexflow-debug.js is the _entire_ VexFlow library. The fiddle in that tutorial _does_ use SVGContext.

A `context` in VexFlow terminology is the class that you use to draw the music. You can either do it on an [HTML Canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial) using VexFlow's `CanvasContext`. Or, by default, you can do it on an [SVG](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial) using VexFlow's `SVGContext`. Everything in VexFlow uses one of these contexts, and this is where the drawing occurs.

> Remember: `context`'s job is to draw, and anything that needs to draw needs `context`'s help to do it.

The key to understanding this (and all of VexFlow's API) is the first 10 lines of code in that Fiddle.

This line makes a shortcut to the complete VexFlow library, calling it VF:
``` JavaScript
var VF = Vex.Flow;
```

The next line gets a reference to the div that will hold the svg of music:
``` JavaScript
var div = document.getElementById("boo")
```

Coming up is where the magic happens. First we make a renderer. 

A `renderer` in VexFlow actually doesn't do much real rendering. It's main job is to create a `context` and create a few shared methods to make it possible for the two very different types of contexts (SVG & Canvas) to use the same API. Typically, once you've created a renderer you'll never reference it again unless you need to resize your svg. However, you'll need to share the `context` almost every time you draw something. 

> A `renderer` creates the `context` for you and resizes the available drawing space.

We pass the `renderer` two arguments.
- 1. The div in which we'll render our SVG.
- 2. A numerical constant representing the kind of `context` we want the renderer to create. (SVG is in all caps both because it's an abbreviation and _also_ because it's a CONSTANT.) In other words, `VF.Renderer.Backends === 3`. If you want, instead of passing `VF.Renderer.Backends.SVG` you can just pass in the number `3` because that's what it is.

``` JavaScript
var renderer = new VF.Renderer(div, VF.Renderer.Backends.SVG);
```

Now we have a renderer. We'll do two things with it, first tell it how big we want our svg to be:
``` JavaScript
renderer.resize(500, 500);
```
And, critically, we'll ask it to give us the `context` it created. Remember when we passed our new `renderer` VF.Renderer.Backends.SVG? (Which is in fact not a backend itself, but just the number `3`.) We told it to make an `SVGContext` for us with that line of code. And here, we ask it to give it to us so that we can use it when we need to draw things:
``` JavaScript
var context = renderer.getContext();
```
So now, our `context` is available to us in the variable `context`. In fact, slip in this line of code, and you can verify that `context` is indeed an instance of `SVGContext`.
``` JavaScript
console.log(context instanceof VF.SVGContext);
```

That SVGContext contains all the classic drawing methods that are used. Methods for drawing lines, rectangles, circles, polygons, etc... It does all the heavy lifting of translating shapes into SVG code for us.

If you've followed this far, I'd recommend you explore the methods in the `context` -- which will give you an idea of how everything in VexFlow is drawn.

I've created a [Fiddle to get you started](https://jsfiddle.net/gristow/r21r2kea/). Take a look at the svgcontext.js code -- and try out the `rect` method first (it's the easiest to understand). Then try making a more complicated path -- using `beginPath`, `moveTo`, `lineTo`, `bezierCurveTo`, `quadraticCurveTo`, and `arc.` You have to call `stroke()` to actually draw the path once you've mapped it out.

Once you understand this very low-level underpinning of the VexFlow library, it becomes much easier to start to dive into the code and understand how the actual drawing works.
