### ISSUE TITLE
How do I match score graphic elements to my data model?

### ISSUE THREAD

**Issue by ciacob** [0xfe/vexflow#560]
Hello all,
First and foremost, thank you for keeping this alive. 

I am working on a desktop music application built using Adobe AIR, that involves (as a secondary task) displaying and editing a musical score. I have been using abcm2ps.exe so far for rendering the score, but I consider switching to Vexflow.

My need, put in one phrase is: assuming that I have my own data model that represents the score, how do I annotate each visual element generated by Vexflow (measure, clef, note, etc.) so that, when user clicks on the visual element, I can figure out that s/he wants to deal with a specific item in my data model?

Notes:
(1) I cannot use the SVG rendering mode; due to Adobe AIR limitations, I'm stuck with Canvas.
(2) I have read the Vexflow tutorial and found nothing that could work with Canvas (I might be wrong, though).

Thank you kindly,
Claudius Tiberiu Iacob

**Comment by gristow** [comment]
Quick version:
- Except for interacting with a rendered SVG element itself, all other elements of the VexFlow api are identical between Canvas and SVG rendering. In your [bootstrap code](https://github.com/0xfe/vexflow/wiki/Understanding-Renderer-&-Context), instead of 
``` javascript
var div = document.getElementById("boo")
var renderer = new VF.Renderer(div, VF.Renderer.Backends.SVG);
```

you'll have:
``` javascript
var canvas = document.querySelector("#your-html-canvas-id");
var renderer = new VF.Renderer(canvas, VF.Renderer.Backends.CANVAS);
```

At that point, I find the easiest thing to do is add event listeners to the canvas element, and check their intersection with various VexFlow elements by:
- using `StaveNote` and other element's `getBoundingBox()` methods
- Calculating the line or space on each staff based on the Y position of the click

There is no built in support for interactive editing, though; you'll need to do that yourself. But, it's something quite a few of us have done at this point in various ways. (See for instance [this editor](https://tests.utheory.com/chord-draw.html) I use. It's using SVG, but with the same principle of comparing clicks/etc... to bounding boxes.)

**Comment by ciacob** [comment]
Thanks, gristow, I appreciate.
