### ISSUE TITLE
triple sharps/flats

### ISSUE THREAD

**Issue by FranciscoPampulha** [0xfe/vexflow#561]
Is it possible to add triple sharps and flats?

**Comment by gristow** [comment]
At present, no, it is not yet possible to add triple accidentals with VexFlow. I'm flagging this with a feature request -- though this may take a bit since they are exceedingly rare in real music.

(They do happen -- for anyone interested in examples, see the "Extreme accidentals" section of [this article](http://homes.soic.indiana.edu/donbyrd/CMNExtremesBody.htm).)

**Comment by sschmidTU** [comment]
You can add them as double sharp sharp:
```js
                if (accidentals[i] === "++") { // triple sharp
                    vfnote.addAccidental(i, new Vex.Flow.Accidental("##"));
                    vfnote.addAccidental(i, new Vex.Flow.Accidental("#"));
                } else if (accidentals[i] === "bbs") { // triple flat
                    vfnote.addAccidental(i, new Vex.Flow.Accidental("bb"));
                    vfnote.addAccidental(i, new Vex.Flow.Accidental("b"));
                }
```
the ordering is so that the single sharp/flat is closer to the notehead.
