### ISSUE TITLE
Make SVG responsive?

### ISSUE THREAD

**Issue by micpob** [0xfe/vexflow#590]
Hello, is there a way to make the SVG or the Stave responsive? 

For what I understand width and height have to be set with pixel values, and therefore are fixed and wont resize with the screen?

**Comment by bneumann** [comment]
Yeah that's not that easy. I also tried making a responsive view. I erase the svg an redraw it. Done properly it is not that slow. 
I will publish an update to my music XML renderer in a few weeks, you can check out how I did it if you like.

**Comment by ulisinn** [comment]
const svg = document.querySelector('svg');
svg.setAttribute('width', '100%');
svg.setAttribute('height', '100%');
svg.setAttribute('viewBox', '0 0 500 500'); // or whatever your defaults were
svg.setAttribute('preserveAspectRatio', 'xMidYMid');

Would that not work?

**Comment by bneumann** [comment]
That squishes the svg but does not recalculate the vex notes. But yes it works too

**Comment by 0xfe** [comment]
Closing this, since it's not something we can do within VexFlow right now.

**Comment by gristow** [comment]
I think this is worth considering not setting width on element.style by default so that we don't override a user's CSS or style settings, or at least adding an option to not do so. it's a relatively easy change in `SVGContext.resize`. Basically, we would just avoid setting a width property on `SVG.style` so that users could define the rendered width however they desire. It could be achieved by adding a third param. Something like:

``` javascript
    resize(width, height, setStyleSize = true) {
      this.width = width;
      this.height = height;
      if(!setStyleSize){
        const attributes = {
          width : width,
          height : height
        };
        this.applyAttributes(this.svg, attributes);
        this.element.style.width = width;
      }
      return this;
    },
```

**Comment by 0xfe** [comment]
That sounds reasonable to me.
