### ISSUE TITLE
How to add lyrics?

### ISSUE THREAD

**Issue by pxwee5** [0xfe/vexflow#626]
Is there a way to add text with vexflow?

**Comment by pxwee5** [comment]
Found annotations. Not alot of examples in the docs though.

**Comment by gristow** [comment]
Yes, annotations are the right solution. If you'd be willing to write one, it'd be great to have a wiki page on annotations for others who may have the same question!

**Comment by bneumann** [comment]
What about textnotes?

**Comment by gristow** [comment]
`TextNote` is also possible -- the difference is that with `TextNote` you'd usually create a voice of `TextNotes` for the lyrics themselves (`TextNote` takes up tick space the same way a `StaveNote` does). So, you'd have two voices, one for the notes, one for the lyrics.

With an `Annotation`, you attach the annotation to a `StaveNote`, so you don't wind up having a second voice.

**Comment by bneumann** [comment]
Thanks @gristow for the explanation. Do expressions like p, pp, fff.. Also work with annotations?

**Comment by mscuthbert** [comment]
Aha!  I had no idea either -- I had always been using TextNotes; great to see that there is another approach.

**Comment by mscuthbert** [comment]
Do Annotations work with hyphens between syllables within a word?

**Comment by AaronDavidNewman** [comment]
Not really.  For Smoosic, we add hyphen or dash manually at the 1/2 way point between 2 notes.  Because the dash may be at the end of a measure or line, your application is responsible for that part.  Annotations are just text.

We also have to manually align the measures vertically, by adding a transform to the svg groups.

![image](https://github.com/0xfe/vexflow/assets/5438280/a070034a-ef62-45d2-81ee-b5fa390f79c8)

![image](https://github.com/0xfe/vexflow/assets/5438280/445565f9-aeda-477c-81d0-240456be5284)
