### ISSUE TITLE
Vex is not defined

### ISSUE THREAD

**Issue by khaldrago96** [0xfe/vexflow#718]
I did the very first tutorial how to build Vexflow. I got all right but sometimes the page won't be load saying `Uncaught ReferenceError: Vex is not defined`

I just dont understand how  the browser compiles

 it. I added 'async' in my script, that references to the library

<img width="251" alt="Capture" src="https://user-images.githubusercontent.com/44110031/67634882-66e26380-f8c1-11e9-9bb3-f1bcc1e26699.PNG">

**Comment by spianoDev** [comment]
I had this same problem when I started my first project. Try adding this script to your index.html page: <script src="https://unpkg.com/vexflow/releases/vexflow-debug.js"></script>

I hope this helps!

**Comment by sschmidTU** [comment]
#719 looks like another helpful tutorial.

(@spianoDev i'm sure you'd make that comment once the PR is approved, but who knows when or if that happens :p )

**Comment by mix3d** [comment]
@khaldrago96 Your issue is your main code is loaded syncronously, but the VexFlow code is loaded asyncronously, which means sometimes your own code is trying to use Vex before Vex is loaded.

You could:

* Have a handler use a setTimeout and check if Vex is defined,  before initializing
* Use an onLoad event listener on the async script, then run your code (https://stackoverflow.com/questions/34076200/check-when-async-javascript-file-is-loaded)
* Not use Async, and make sure the Vex source is defined/loaded before your script is. (Like it's 2008)
