### ISSUE TITLE
Option for dynamic layout

### ISSUE THREAD

**Issue by thibault** [0xfe/vexflow#734]
Hi,

I'm just starting to use this library, and it seems awesome. I'm a bit puzzled about the way staves layout is supposed to work, though.

First, I followed the EasyScore tutorial, but it took me a long time and quite some digging to realize a stave is only supposed to hold one measure. Adding more bars requires adding new staves. Is that correct? If that is, and since it's such an important feature, may I suggest to add this info in a more proeminent place in the tutorials?

I also have some problems understanding how the layout is supposed to work. As far as I can see, in every examples I could find, setting the layout is done manually, by setting absolute coordinates to successive staves.

Let's say I want to display some music on screen with different sizes (e.g a responsive web app). How should I approach it? Is there a built-in way to do it, because I could'nt find it?

Now if someone more competent than I am could just point me in the correct directions, I'd be happy to submit PR to maybe clarify the tutorials to help first-timers like myself.

**Comment by 0xfe** [comment]
Hi @thibault -- For now, you'll have to lay things out yourself unfortunately. I have WIP `Page` and `Layout` classes that are unfinished, with no ETA on them :-) That said, for specific cases, custom automatic layouts are pretty easy to do, since the staves will both provide a recommended width, and render correctly at arbitrary widths. So all you need to do is decide when and how much to break lines, and re-render everything on window resize events.

(Obviously, building a generic layout class is more complicated, but this should get you started. Vextab is a good example of a library that does this kind of simple auto layout.)

Mo.

**Comment by thibault** [comment]
Hi @0xfe. Thank you for taking the time to respond.

Dedicated code to format the laout would be awesome of course, but simply adding what you just said to me somewhere in the tutorial would be super-useful IMO. Maybe a simple piece of code sample with a generic use case would bring a lot.

Anyway, thank you for your reply.
