### ISSUE TITLE
Add support for chord symbols

### ISSUE THREAD

**Issue by 0xfe** [0xfe/vexflow#776]
Right now we have text-based chord symbols (using UTF codes) that don't look too great. Add support for prettier chord symbols taking glyphs from the current font.

**Comment by AaronDavidNewman** [comment]
Is anyone working on this?  
I thought a good step would be to add the glyphs from the 'chord symbols' section of the font to the vexflow glyphs.   I was able to do this with the Petaluma fonts, but with the Bravura fonts I get the following error from opentype.js.  Is it possible this font file is corrupted?

Windows 10 user.

C:\Users\Daddy\Documents\GitHub\vexflow\tools\smufl>node smufl_fontgen.js fonts/Bravura.otf ..\..\src\fonts\bravura_glyphs.js

C:\Users\Daddy\Documents\GitHub\vexflow\node_modules\opentype.js\dist\opentype.js:4020
                    throw new Error('Object ' + o + ' already has key ' + key);
                    ^

Error: Object [object Object] already has key 0
    at entriesToObject (C:\Users\Daddy\Documents\GitHub\vexflow\node_modules\opentype.js\dist\opentype.js:4020:20)
    at parseCFFDict (C:\Users\Daddy\Documents\GitHub\vexflow\node_modules\opentype.js\dist\opentype.js:4058:13)
    at parseCFFPrivateDict ...
(C:\Users\Daddy\Documents\GitHub\vexflow\tools\smufl\smufl_fontgen.js:61:23)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

**Comment by AaronDavidNewman** [comment]
I downloaded the Bravura font from the steinbergmedia git repository and it fixed the problem. 
Now I'm wondering about things like (sus4).  Do we want these letters/digits to be in the font also?  The numbers used for time signatures I don't think will work.  Same for things like 'IV V7' for analysis chords.

**Comment by 0xfe** [comment]
Hi Aaron -- No one's working on this yet, thanks for digging in. We have a two options:

1) Use Bravura for all text (by default.)
2) Let the user download a text font separately (with HTML `link` + CSS) and render that.

The first will be more consistent and better looking, but will further bloat the package. We could add an API to asynchronously load fonts if requested.

The second is more flexible I think, and you can sort of already do that today, except not in a consistent way, and there's no documentation.

**Comment by 0xfe** [comment]
(Also, pulling chord symbols from the font into Vexflow is a good idea.)

**Comment by h-sug1no** [comment]
FYI:

<https://w3c.github.io/smufl/gitbook/tables/chord-symbols.html>

> Implementation notes
>
>These symbols are designed to combine with accidental symbols (accidentalSharp and accidentalFlat) from the music font and the letters A–G (for root and bass alterations), lower case letters (for chord qualities, e.g. “maj” and “min”) and numbers (for chord extensions or tensions) from any standard text font to produce complete chord symbols.
>
>Scoring applications should be able to create strings with complex formatting, e.g. superscript and subscript characters, small digits stacked on top of each other, and scale these symbols to any arbitrary size in order to produce satisfactory chord symbols with a wide variety of visual appearances.

**Comment by AaronDavidNewman** [comment]
Thanks, I have added these symbols to my fork and I am trying to figure out how to submit a pull request.  I have stuff in my fork that others may not want, is the thing, and I've not done this before on github.  Do I create a separate issue just for the pull request?

**Comment by AaronDavidNewman** [comment]
I created a new forked repository and submitted the symbols from there.

>> 1. Use Bravura for all text (by default.)
>> 2. Let the user download a text font separately (with HTML link + CSS) and render that.

option 1 does seem bloat-y to me.  Can't we just let the user select the font as they would with for annotations?  And then assume the browser can find the font, either because they included a link to it, or it is built in.  
I was thinking the chord symbols would be similar to annotations, with options for position and possibly something fluent, like addSymbol('C7').addFlat(5).addFlat(9).over('F').  We can also parse a string like 'C7(b5b9)/F', but it seems like starting with the fluent way is best.

**Comment by sschmidTU** [comment]
Just adding a reference to #786, which seems to be at least a part of the solution.

**Comment by AaronDavidNewman** [comment]
This is still on my own branch, but this is what I have so far if anyone wants to see.  This is using symbol glyphs and browser fonts.  It mostly looks good, but it needs some kerning hints, esp the 'over' / symbol.

![image](https://user-images.githubusercontent.com/5438280/80892358-0298c600-8c8f-11ea-85cc-911e8a52b28c.png)

![image](https://user-images.githubusercontent.com/5438280/80892365-18a68680-8c8f-11ea-80c7-0df0e99eaf9d.png)

https://aarondavidnewman.github.io/vex_chords/tests/flow.html?module=ChordSymbol

**Comment by AaronDavidNewman** [comment]
Some screenshots:

Top chord changes, pseudo-kerning makes superscript closer to 'A' so 'A' and 'E" look more even:

![image](https://user-images.githubusercontent.com/5438280/80995767-685a8e80-8e04-11ea-974a-d58e2a98340f.png)

Petaluma font, same concept:

![image](https://user-images.githubusercontent.com/5438280/80995861-8cb66b00-8e04-11ea-9fe6-1a67ea6e93eb.png)

Stacked and non-stacked chord extensions, Bravura:
![image](https://user-images.githubusercontent.com/5438280/80995923-a5268580-8e04-11ea-8453-be27140dce3f.png)

Petaluma
![image](https://user-images.githubusercontent.com/5438280/80996010-c4251780-8e04-11ea-8deb-70bc8cb9a752.png)

Bottom chord changes, analysis-style.  Bravura:
![image](https://user-images.githubusercontent.com/5438280/80996056-d43cf700-8e04-11ea-8209-df6a80602bd5.png)

Petaluma:
![image](https://user-images.githubusercontent.com/5438280/80996109-e880f400-8e04-11ea-96f9-4696cf331c6a.png)

Multiple chords per vex note:
![image](https://user-images.githubusercontent.com/5438280/80996200-0b130d00-8e05-11ea-938d-bb7a961b6b01.png)

Horizontal justification: center, left, right, stem.  Right ends up being strangely left, since origin is always the startX.

![image](https://user-images.githubusercontent.com/5438280/80996339-444b7d00-8e05-11ea-92e2-8b49758aa201.png)

**Comment by AaronDavidNewman** [comment]
Font size tests:
![image](https://user-images.githubusercontent.com/5438280/81134897-d3e34f80-8f1b-11ea-8d68-aad8a6af7a09.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman is this topic close or is there anything pending?

**Comment by AaronDavidNewman** [comment]
Yes this can be closed.

**Comment by rvilarl** [comment]
Thanks.
@0xfe this can be closed.

**Comment by ronyeh** [comment]
> with the Bravura fonts I get the following error from opentype.js. Is it possible this font file is corrupted?

**Short answer: YES, the font file is corrupted by git.**

Medium answer: When we git add OTF files, we get this warning (that quickly scrolled off my terminal so I missed it the first time). `warning: CRLF will be replaced by LF in tools/smufl/fonts/Bravura.otf. The file will have its original line endings in your working directory`. I think the solution is to add `*.otf binary` to the `.gitattributes` file.


LONG answer: I was working on https://github.com/0xfe/vexflow/pull/1158 and two days ago I was able to run my opentype.js scripts to extract the paths (I had upgraded Bravura and Petaluma). However, today I was getting errors on all the fonts!

I banged my head on it for a while, and even uninstalled Bravura/Petaluma/Gonville from my macOS font book (font registry). I also restarted my computer. No luck.

I googled the error messages, and eventually I found your post! Of course re-downloading all the original font files works. But I needed to figure out what was corrupting the files. (I noticed the macOS Finder preview no longer showed the font version 1.392 for the Bravura file).

Anyways, I eventually git added the file, and luckily caught the warning this time.

Even after you git commit, everything works fine! **It's because git doesn't modify your local working copy.**

However, if you delete the OTF file, and check it out again from the git data store, you'll notice that the OTF file is finally corrupted. 

:-(

Anyways, OTFs can be corrupted by git when added, because git changes line endings. Hopefully the .gitattributes flag will fix this.

**Comment by ronyeh** [comment]
https://git-scm.com/docs/git-config#:~:text=CRLF%20conversion%20bears%20a%20slight%20chance%20of%20corrupting%20data.

> CRLF conversion bears a slight chance of corrupting data.

Hopefully someone in the future will benefit from this. Make sure you tell git to treat OTF (and possibly other files) as binary!

**Comment by ronyeh** [comment]
Here are the two opentype.js errors I got:

`Error: Object [object Object] already has key 0`
`throw new Error('Invalid b0 ' + b0); Error: Invalid b0 24`

(This comment is to help the next developer who runs into this issue, and is searching the web for matching error messages.)

Add: `*.otf binary` to the end of your `.gitattributes` file!
