### ISSUE TITLE
Articulation size

### ISSUE THREAD

**Issue by amitgur** [0xfe/vexflow#814]
Hey all
I'm using the bow-up bow-down articulations as in the test https://www.vexflow.com/tests/?module=Articulation
The size of the symbol is too big for my eyes. especialy the bow down. 
In line 237 here https://github.com/0xfe/vexflow/blob/master/src/articulation.js the font is set to 38. Size of 30 for that will look great

Any way to change that exept hard coding my node_module library?
Mybe this should be an option to set?

**Comment by sschmidTU** [comment]
```js
const art = new Vex.Flow.Articulation();
art.render_options.font_scale = 30
```
shouldn't this work?

**Comment by amitgur** [comment]
I though that there is a simple way, Thats worked thanks 
https://bandpad.co/bandpadV2/#/online-mockup/HavaNarimaUku/guitar/en/keyTag

**Comment by sschmidTU** [comment]
@amitgur no problem. i see you probably have a slight error in your dotted notes creation:
the "r" for rest has to come after the "d"s (dots), not before. otherwise the positioning won't be correct. we had that problem too ^^
![image](https://user-images.githubusercontent.com/33069673/100139385-b1049280-2e8f-11eb-95b2-80680a339f8d.png)

**Comment by sschmidTU** [comment]
@amitgur Can you close this issue then? Then everyone knows it's solved :)

**Comment by amitgur** [comment]
Thank you @sschmidTU
