### ISSUE TITLE
More than one repetition

### ISSUE THREAD

**Issue by newlandsvalley** [0xfe/vexflow#832]
How should one represent a simple section of the score which is to be repeated more than once (without voltas)?

**Comment by sschmidTU** [comment]
It looks like there is no definitive musical notation for this.
If you have lyrics, the number of repetitions seem implicit from the number of verses (see below).
Otherwise, write text above the repetition ("play x times") or something.
https://music.stackexchange.com/questions/74084/is-there-a-definitive-notation-for-multiple-repeats

**Comment by newlandsvalley** [comment]
Many thanks, Simon.  I have no lyrics.  I ask because I translate from ABC notation which represents it with multiple colons, but I've no idea how this should be rendered.  They use the double colon in their rendering of the ABC but I have seen no evidence for it.  Maybe I'll take your advice and just use text.

**Comment by newlandsvalley** [comment]
Closing this because it is not a VexFlow issue.
