### ISSUE TITLE
Add svg title & description as parameters to renderer for SEO (and accessibility?)

### ISSUE THREAD

**Issue by gusmoney** [0xfe/vexflow#835]
First of all, thanks for your fantastic work on vexflow! I'm building a [scale-lookup app](https://www.scale-lookup.com) with it.

I'd like to have the option of setting the title and description within the svg for the purpose of SEO. I suppose this might also have a value for accessibility. (Possibly I'd also have an aria-labelledby tag - cf. https://css-tricks.com/accessible-svgs/#2-inline-svg)

I guess I could do this and create a PR, but I would appreciate your thoughts before I do. Is this a good idea?

**Comment by gristow** [comment]
At [uTheory](https://utheory.com) we do this using aria-labeledby for all of our SVGs, for the purposes of accessibility. (We don't use the SVG `<title>` element to avoid having a tool tip pop-up for sighted users.) As you point out, there are a several ways to do this, depending on the presentation of the SVG (namely, `alt` tags on SVGs loaded by an `img` element, `<title>` elements in inline SVGs, and `aria-labeledby` for either).

Because of that, I think it makes the most sense to leave it to users of vexflow to grab the svg (or canvas) element and label it accordingly:

```javascript
function labelSvg(svgId, labelText) {
  const svg = document.getElementById(svgId);
  const parent = svg.parentElement;
  const label = document.createElement('label');
  const labelId = `${svgId}-label`;
  label.id = labelId;
  label.setAttribute('for', svgId);
  label.classList.add('sr-only'); // or whatever you use for accessibly hidden text
  label.innerText = labelText;
  svg.setAttribute('aria-labelledby', labelId);
  parent.appendChild(label);
  return label;
}
```

**Comment by gusmoney** [comment]
Ah - yes you are probably right.

Thanks for commenting!
