### ISSUE TITLE
'GetKeyParts' accidentals missing in regex?

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#852]
What is the reason why the in this function the accidentals n,bb,## are not allowed? 
`const regex = /^([cdefgab])(b|#)?(mel|harm|m|M)?$/;`

_Originally posted by @rvilarl in https://github.com/0xfe/vexflow/pull/851#discussion_r594548506_

**Comment by rvilarl** [comment]
I refer to line
https://github.com/0xfe/vexflow/blob/5eb92750f65fe07d6115073d8e3be1a8fa2c191c/src/music.js#L217

I believe it should be
`const regex = /^([cdefgab])(b|bb|n|#|##)?(mel|harm|m|M)?$/;`

like in
 https://github.com/0xfe/vexflow/blob/5eb92750f65fe07d6115073d8e3be1a8fa2c191c/src/music.js#L193

**Comment by rvilarl** [comment]
In fact I would suggest to remove the function `GetKeyParts` and include the scales in `GetNoteParts` due to the fact that `(mel|harm|m|M)?` is optional and `GetKeyParts` is only instanciated twice in `keymanager.js`

**Comment by 0xfe** [comment]
> What is the reason why the in this function the accidentals n,bb,## are not allowed?

Is `Cbb` a valid key. Is a `C## major` a valid scale? I've never seen that before. Also I don't know what accidentals would apply to the notes in the scale.

Maybe @gristow or @mscuthbert have thoughts.

**Comment by rvilarl** [comment]
@0xfe  OK I had not understood correctly the aim of the function. I believe you are right. I will wait to see if there are additional thoughts.

**Comment by mscuthbert** [comment]
I don't think that Vexflow needs to support double-accidentals in key and scale names.  Music21 supports them, because theoretically they could exist, but no notation software I know can render them.  (Indeed, there's no standardization for how key signatures would work: for G# major, for instance, do you write F## C# G#...etc...B# or F# C# G#...etc...B# F## (that would draw the most attention to the double sharp).  I don't think that it needs to be there.

Btw -- off topic, but just to watch out in the future since it has bitten so many previous software packages: avoid ever using CCC, CC, C, c, cc, ccc to mean different octaves if you're using a system where "b" is also used to mean flat, since "bbb" is completely ambiguous ("b-double-flat? bb-flat? bbb-natural?")

**Comment by rvilarl** [comment]
@0xfe @mscuthbert now that I have learnt the differen between these functions I would suggest to split the type:
`
export interface NoteParts {
  root: string;
  accidental: string;
  type?: string;
}
`
in two:
`
export interface NoteParts {
  root: string;
  accidental: string;
}`
`export interface KeyParts {
  root: string;
  accidental: string;
  type: string;
}
`

Would you agree? If yes I will include it in the first **airbnb** PR

**Comment by rvilarl** [comment]
@0xfe @mscuthbert and talking about keys, why is only dorian and mixolydian included. Should I include in the next **airbnb** PR also Ionian, Phyrgian, Lydian, Aeolian and Locrian?

**Comment by mscuthbert** [comment]
Phrygian and Lydian seem uncontroversial.  Locrian too, I suppose (modern invention but everyone knows it).  Ionian and Aeolian, we need to establish if it's good to have two ways of notating the same thing.  I think probably, because definitely Aeolian is different in conception from Minor, and once we have Aeolian in, Ionian needs to go in.

**Comment by 0xfe** [comment]
Those modes are not used within VexFlow, so it doesn't really matter. I'm okay with anything here.

**Comment by rvilarl** [comment]
@0xfe @mscuthbert I will do a PR once we close #856 including:
- Phrygian,...
- split of current interface NoteParts in NoteParts and KeyParts.

**Comment by 0xfe** [comment]
Let's hold off on this one as well until the TS changes are better understood and reigned in.

**Comment by rvilarl** [comment]
Added to #865
