### ISSUE TITLE
Migration: addModifier

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#904]
In the different classes the parameters of `addModifier` is not consistent. There are two options:
`addModifier(index, modifier)`
`addModifier(modifier, index)`

**Comment by rvilarl** [comment]
@wassertim this also affects `accidentals`
@0xfe what is your preference?

**Comment by wassertim** [comment]
It is not related to the ts-migration, so we don't have to change it during the migration and we can fix it later. But would be really nice to fix it yes. 

If we fix it now, it can be a breaking change for those who uses addModifier. 
If we don't fix it we would have to mark parameters as type of `any` which is ugly.

About the order. For me `addModifier(index, modifier)` makes more sense than the other

**Comment by rvilarl** [comment]
For completeness we have now:
`Tickable.addModifier(modifier)`
`Note.addModifier(modifier, index = 0)`
`StaveNote.addModifier(index, modifier)`
`Stave.addModifier(modifier, index)`

As @wassertim stated the compiler complains if we do not use `any` which disables type checking.

Looking at the test it is really misleading how the tests defer depending on the class being used to access `addModifier`

I would fix it now.

**Comment by 0xfe** [comment]
Yikes, that's a mess!

I think that `addModifier` is never called on `Tickable` and `Note` (except for unit tests), so it's possible we can leave them as abstract methods.

I'd suggest throwing a `MethodNotImplemented` exception in `Tickable` and `Note` and check what fails (outside of the explicit tests for those methods.)

We can then use that to figure out the the right path.

**Comment by 0xfe** [comment]
Ugh no, I was wrong -- other derivatives of `Note` like `TabNote` call `this.addModifier(modifer)`, so they are used.

I think we might need to figure out a standard convention, and warn for usage of the unsupported convention. Something like this:

```typescript
// TODO: deprecate and remove after all callers identified
function ResolveAddModifierParams(a: number | Modifier, b: number | Modifier): {index: number, modifier: Modifier} {
  if (typeof a === number) {
    console.warn("deprecated call signature to addModifier, use addModifier(modifier, index) instead");
    return({index: a, modifier: b});
  } else {
    return({index: b, modifier: a});
  }
}

addModifier(a: number | Modifier, b: number | Modifier) {
  let {index, modifier} = ResolveAddModifierParams(a, b);

  // .. use index and modifier as normal ...
}
```

**Comment by rvilarl** [comment]
@0xfe looking at your example code, it seems that you suggests to got for the `addModifier(modifier, index)`. I would go for the `addModifier(index, modifier)` as suggested by @wassertim this is also in line with the majoritiy of  implementations:

`StaveNote.addModifier(index, modifier)`
`StaveNote.addAccidental(index, modifier)`
`StaveNote.addArticulation(index, modifier)`
`StaveNote.addAnnotation(index, modifier)`

**Comment by 0xfe** [comment]
Some derivatives of `Note` don't have an index (and don't need to), so a more meaningful API would be `addModifier(modifier, index = null)`. It's only `StaveNote` and `TabNote` that have indexes.

So with `addModifier(modifier, index)`, derivatives can just call `addModifier(foo)`, as opposed to `addModifier(null, foo)`.

**Comment by rvilarl** [comment]
ok then I would suggest to leave those untouched:
`StaveNote.addAccidental(index, modifier)`
`StaveNote.addArticulation(index, modifier)`
`StaveNote.addAnnotation(index, modifier)`
and change only:
`StaveNote.addModifier(index, modifier)`

right?

**Comment by 0xfe** [comment]
Yes, agreed.

**Comment by 0xfe** [comment]
Also, I think addAccidental/Articulation/... should be deprecated
eventually. I'd like our public uses to tread towards the new APIs:
Factory, System, EasyScore, etc.

**Comment by rvilarl** [comment]
The output of the tests is very messy. I will make a PR shortly.

**Comment by rvilarl** [comment]
@0xfe PR is there, have fun!

**Comment by mscuthbert** [comment]
> Also, I think addAccidental/Articulation/... should be deprecated eventually. I'd like our public uses to tread towards the new APIs: Factory, System, EasyScore, etc.

Please don't deprecate them.  These are low-level systems for the low-level API that I love about VexFlow, because it allows me to use it in my projects without needing to go through Factory, System, etc. -- which are great for displaying scores but poorer for manipulating them and transforming them with lightning speed and while preserving references to individual StaveNote objects etc. 

My feeling (expressed when EasyScore, etc. started) is that Factory and EasyScore, etc. are really best conceived as separate projects bundled with and built on top of VexFlow in terms how they're organized -- VexFlow provides an abstraction layer between individual musical objects and their graphical representation.  While EasyScore, etc. provides an abstraction layer between scores and individual musical objects.  But one of the most powerful parts of VexFlow is that others can build other layers above it (like Cyril's note game, or OSMD, or my music21j).  

I DO think that encouraging the public to use easier abstraction layers is important, and maybe branching EasyScore/Factory, etc. to be its own thing with its own home-page, quick start, etc. is the best way to make it clear that users who just want to put a score in their webpage shouldn't be worrying about `.formatter.joinStaves()` etc.

**Comment by 0xfe** [comment]
@mscuthbert I hear ya loud and clear. It's a bit of an API wart, and maybe we can think of a more consistent way to give you the control you need.

**Comment by 0xfe** [comment]
(i.e., okay not to deprecate for now, but let's still think about how to clean it up.)
