### ISSUE TITLE
Incorrect formatting for multiple voices

### ISSUE THREAD

**Issue by deemaagog** [0xfe/vexflow#990]
Hi. I'm experiencing incorrect formatting for multiple voices when note in voice 1 and note in voice 2 have different stemmings (same for 1.2.93 and 3.0.9)

![image](https://user-images.githubusercontent.com/16086591/119226051-11f3e700-bb10-11eb-9c30-44796099632f.png)

jsfiddle:   https://jsfiddle.net/aodxLwm1/3/

I believe notes should be aligned regardless stemmings. This is how it looks like in Musescore

![image](https://user-images.githubusercontent.com/16086591/119226124-55e6ec00-bb10-11eb-9431-51ff9bd49b16.png)

**Comment by AaronDavidNewman** [comment]
It looks like these issues have been fixed in the latest version of Vex.  Here is how it renders in Smoosic:

![image](https://user-images.githubusercontent.com/5438280/119240974-0f49bf80-bb19-11eb-9ffa-2f4e44e31acf.png)

**Comment by deemaagog** [comment]
@AaronDavidNewman Hmm... In the provided jsffiddle latest version 3.0.9 is in use. I've slightly modified multivoice example from tutorial. 
How do you do formatting in Smoosic?

**Comment by AaronDavidNewman** [comment]
Hmm....good question.  It looks like this works fine in 3.0.9, too.  It's how you are joining the voices.  you join them 1 at a time, and format them together.   Otherwise, it won't justify the voices together.  This gets me all the time, I always forget this (and it seems like kind of a strange rule, tbh).

``` javascript
var formatter = new VF.Formatter().joinVoices([voicesTreble[0]]).joinVoices([voicesTreble[1]]).format(voicesTreble, 350);
```

https://jsfiddle.net/AaronDavidNewman/j1qx0wgu/

**Comment by deemaagog** [comment]
Thanks a lot!

**Comment by compilelife** [comment]
osmd has a fix for this : https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/414
(though not so elegant）

Hope some vexflow way to solve this.

I think that 'join voice 1 at a time' is not a correct way to use formatter. Since joinVoice would share only one modifier context around every voice in parameter. Voices in same stave should share one modifier context, which means joinVoice once.

**Comment by sschmidTU** [comment]
@compilelife you should probably open a new issue, it's easy to overlook a closed one.
Also maybe add more details. Is it the same problem as in the first 2 images in this thread?
